export const researchData2018 = [
  {
    title: "ANTIFUNGAL ACTIVITY OF BITTER VINE (Mikania micrantha) LEAF EXTRACT ON Aspergillus flavus",
    publishedAt: 2018,
    researchId: "2018-001",
    author: "SHEIMIL B. MADRONES, JAN ALEXIS J. ARROYO, MAREX C. FAJARDO",
    citation: "Madrones, S. B., Arroyo, J. A. J., Fajardo, M. C. (2018). ANTIFUNGAL ACTIVITY OF BITTER VINE (Mikania micrantha) LEAF EXTRACT ON Aspergillus flavus.",
    abstract: "This study aims to know the antifungal activity of bitter vine (mikania micrantha) leaf extract on aspergillus flavus. Results revealed that 100% and 50% extract showed antifungal activity. The researchers concluded that 100% and 50% bitter vine leaf extract had an antifungal activity on aspergillus flavus.",
  },
  {
    title: "ANTIFUNGAL ACTIVITY OF GUYABANO (Annona muricata) LEAF EXTRACT ON Aspergillus flavus",
    publishedAt: 2018,
    researchId: "2018-002",
    author: "MILDRED M. MONTALBAN, REINA DANECCA P. PLANCO",
    citation: "Montalban, M. M., Planco, R. D. P. (2018). ANTIFUNGAL ACTIVITY OF GUYABANO (Annona muricata) LEAF EXTRACT ON Aspergillus flavus.",
    abstract: "This study aimed to find out the antifungal activity of guyabano leaf extract on Aspergillus flavus. Results revealed that 50% and 100% concentrations were effective, with 50% being the most effective.",
  },
  {
    title: "CYTOTOXIC ACTIVITY OF GUAVA, JACKFRUIT AND COCONUT LEAVES EXTRACT USING BRINE SHRIMP LETHALITY ASSAY",
    publishedAt: 2018,
    researchId: "2018-003",
    author: "JESSA MAE S. LOPEZ, PEARL VENICE C. SEPAYA, CRYSTELLE ANN R. MARQUILENCIA",
    citation: "Lopez, J. M. S., Sepaya, P. V. C., Marquilencia, C. A. R. (2018). CYTOTOXIC ACTIVITY OF GUAVA, JACKFRUIT AND COCONUT LEAVES EXTRACT USING BRINE SHRIMP LETHALITY ASSAY.",
    abstract: "Fresh Psidium guajava, Artocarpus heterophyllus and Cocos nucifera leaves were tested. Results revealed that the ethanolic extracts showed good brine shrimp cytotoxic activity (LC50 values below 1000 ug/mL).",
  },
  {
    title: "THE PESTICIDAL EFFECT OF SKY FRUIT, CHILI PEPPER, AND BETEL LEAVES POWDER ON GOLDEN APPLE SNAILS",
    publishedAt: 2018,
    researchId: "2018-004",
    author: "JHISTINE CLYDE A. BLANCAFLOR, JIMSON G. KUSOG, NOVELYN R. CLAMOR",
    citation: "Blancaflor, J. C. A., Kusog, J. G., Clamor, N. R. (2018). THE PESTICIDAL EFFECT OF SKY FRUIT, CHILI PEPPER, AND BETEL LEAVES POWDER ON GOLDEN APPLE SNAILS.",
    abstract: "Sky fruit powder and commercial pesticides showed the greatest number of dead snails. ANOVA revealed sky fruit powder has a high significant effect on killing golden apple snails.",
  },
  {
    title: "PESTICIDAL EFFECT OF MAKABUHAY (Tinospora rumphii Boerl) ON THE PHILIPPINE MILK TERMITES",
    publishedAt: 2018,
    researchId: "2018-005",
    author: "KRISTINE VERL S. MANDARIO",
    citation: "Mandario, K. V. S. (2018). PESTICIDAL EFFECT OF MAKABUHAY (Tinospora rumphii Boerl) ON THE PHILIPPINE MILK TERMITES.",
    abstract: "The study used 150g, 300g, and 400g concentrations of stem extract. Results show that makabuhay stem extract is effective in killing Philippine milk termites.",
  },
  {
    title: "THE POTENTIAL OF PEANUT (Arachis hypogaea) SHELL STARCH AS A COMPONENT IN MAKING BIO-PLASTIC",
    publishedAt: 2018,
    researchId: "2018-006",
    author: "CYRA JANNE C. MASCULIN, AELRED MAURICE R. TORMON, EMMANUEL M. ESCAÑO JR.",
    citation: "Masculin, C. J. C., Tormon, A. M. R., Jr., E. M. E. (2018). THE POTENTIAL OF PEANUT (Arachis hypogaea) SHELL STARCH AS A COMPONENT IN MAKING BIO-PLASTIC.",
    abstract: "Various treatments using peanut shell starch solution were tested. Results revealed that peanut shell starch is not an effective component due to the resulting bio-plastic's fragility.",
  },
  {
    title: "ANTIBACTERIAL ACTIVITY OF AHITO (Tagetes erecta) LEAF OINTMENT ON Staphylococcus aureus",
    publishedAt: 2018,
    researchId: "2018-007",
    author: "ERBIE MARIE S. RANGAS, JONNAH G. PADILLA, ALEHA MARIE H. ANGELADA",
    citation: "Rangas, E. M. S., Padilla, J. G., Angelada, A. M. H. (2018). ANTIBACTERIAL ACTIVITY OF AHITO (Tagetes erecta) LEAF OINTMENT ON Staphylococcus aureus.",
    abstract: "This research assessed the effectiveness of Ahito leaf ointment against Staphylococcus aureus skin infections. It discusses how bacteria normally reside on the skin but can cause infections like cellulitis or boils.",
  },
  {
    title: "EFFECTIVENESS OF COMPLETE IDENTITY INFORMATION BAR CODE SYSTEM VERSUS MANUAL CHECKING",
    publishedAt: 2018,
    researchId: "2018-008",
    author: "ALVIE JOHN P. ALAG, SCHARLET T. LIPA, JAMES IVAN P. SUMINGIT",
    citation: "Alag, A. J. P., Lipa, S. T., Sumingit, J. I. P. (2018). EFFECTIVENESS OF COMPLETE IDENTITY INFORMATION BAR CODE SYSTEM VERSUS MANUAL CHECKING.",
    abstract: "Tested at the senior high guard house, results revealed that time spent authenticating student information was significantly reduced compared to manual checking.",
  },
  {
    title: "ANTIFUNGAL EFFECT OF HAUILI (Ficus septica blanco) LEAF EXTRACT",
    publishedAt: 2018,
    researchId: "2018-009",
    author: "JANINE SEPTER D. PADILLA, SAILESA G. SAMAR, RANNILYN P. NAVIO",
    citation: "Padilla, J. S. D., Samar, S. G., Navio, R. P. (2018). ANTIFUNGAL EFFECT OF HAUILI (Ficus septica blanco) LEAF EXTRACT.",
    abstract: "One kilogram of Hauili leaves was extracted via rotary evaporation. Results revealed that 100% and 50% concentrations showed antifungal activity against Aspergillus flavus.",
  },
  {
    title: "AN ASSESSMENT ON THE COLOR CHANGE OF BLUE TERNATE FLOWER EXTRACT AS NATURAL PH INDICATORS",
    publishedAt: 2018,
    researchId: "2018-010",
    author: "JOHN JOSHUA C. DE GUIA, JULIA SHANE R. BARRIOS, JUN SUN A. MAGEANAM",
    citation: "De Guia, J. J. C., Barrios, J. S. R., Mageanam, J. S. A. (2018). AN ASSESSMENT ON THE COLOR CHANGE OF BLUE TERNATE FLOWER EXTRACT AS NATURAL PH INDICATORS.",
    abstract: "Findings showed that Blue Ternate (Clitoria ternatea) pH indicators demonstrate color change when subjected to solutions with different pH values from 0 to 14.",
  },
  {
    title: "TURMERIC (Curcuma longa) EXTRACT AS AN ANTIBACTERIAL FOR Staphylococcus epidermidis",
    publishedAt: 2018,
    researchId: "2018-011",
    author: "PAMELA SUE HILADA, BASHRACEL MARIE SALMORIN, DANICA DANIELE SERRANO",
    citation: "Hilada, P. S., Salmorin, B. M., Serrano, D. D. (2018). TURMERIC (Curcuma longa) EXTRACT AS AN ANTIBACTERIAL FOR Staphylococcus epidermidis.",
    abstract: "Agar well diffusion was used to test various concentrations. Turmeric extract showed an antibacterial effect on Staphylococcus epidermidis in terms of zone of inhibition.",
  },
  {
    title: "BLOOD CLOTTING POTENTIAL OF (Gliricidia sepium) LEAF AND CAMBIUM EXTRACT",
    publishedAt: 2018,
    researchId: "2018-012",
    author: "EMMANUEL J. JORDAN, SHAINA FAITH S. LAQUIHON, CARL JOVE PINEDA",
    citation: "Jordan, E. J., Laquihon, S. F. S., Pineda, C. J. (2018). BLOOD CLOTTING POTENTIAL OF (Gliricidia sepium) LEAF AND CAMBIUM EXTRACT.",
    abstract: "Utilized Lee-White's Method. ANOVA revealed no significant difference in clotting time compared to normal blood, and in some cases, it took longer for the blood to clot.",
  },
  {
    title: "EFFECTIVENESS OF MOBILE ACTIVATED POWER SWITCH (MAPS)",
    publishedAt: 2018,
    researchId: "2018-013",
    author: "JESSIE ANN C. BERONDO, JOEY F. CABALLERO, NOVIE MARIE M. BEÑARES",
    citation: "Berondo, J. A. C., Caballero, J. F., Beñares, N. M. M. (2018). EFFECTIVENESS OF MOBILE ACTIVATED POWER SWITCH (MAPS).",
    abstract: "A remote-controlled device tested at a distance of 3km. Results showed the device is effective in saving time, energy, and money compared to manual switching.",
  },
  {
    title: "THE ACCEPTABILITY OF COCONUT (Cocos nucifera) OIL AS A SHOE POLISH",
    publishedAt: 2018,
    researchId: "2018-014",
    author: "CHRISTINE JOY C. PATCHES, SAINT PATRICK P. ENERIO, PERCY ANNE A. HUESCA",
    citation: "Patches, C. J. C., Enerio, S. P. P., Huesca, P. A. A. (2018). THE ACCEPTABILITY OF COCONUT (Cocos nucifera) OIL AS A SHOE POLISH.",
    abstract: "Tested by 20 students. Coconut oil shoe polish was found acceptable in terms of effect, duration of shine, and smell compared to commercial products.",
  },
  {
    title: "FUNGICIDAL ACTIVITY OF THE DIFFERENT CONCENTRATIONS OF SEA SALT SOLUTION ON Candida albicans",
    publishedAt: 2018,
    researchId: "2018-015",
    author: "ELLAINE RARE M. JUNIO",
    citation: "Junio, E. R. M. (2018). FUNGICIDAL ACTIVITY OF THE DIFFERENT CONCENTRATIONS OF SEA SALT SOLUTION ON Candida albicans.",
    abstract: "Agar Well Diffusion was used for testing. Results showed that different concentrations of sea salt solution have no antifungal effect on Candida albicans.",
  },
  {
    title: "COCONUT OIL (Cocos nucifera) AS AN EFFECTIVE HOUSEFLY (Musca domestica) ELMINATOR",
    publishedAt: 2018,
    researchId: "2018-016",
    author: "KENYA M. COMEDA",
    citation: "Comeda, K. M. (2018). COCONUT OIL (Cocos nucifera) AS AN EFFECTIVE HOUSEFLY (Musca domestica) ELMINATOR.",
    abstract: "Determined the effectiveness of coconut oil versus a chemical solution. Analysis showed coconut oil is effective in killing houseflies through multiple trials.",
  },
  {
    title: "ANTIBACTERIAL EFFECT OF SINAW SINAW (Peperomia pellucida) LEAF EXTRACT ON Staphylococcus aureus",
    publishedAt: 2018,
    researchId: "2018-017",
    author: "KATRINA ANN L. DELA TORRE, SIERRA MAY M. BABIARTE",
    citation: "Dela Torre, K. A. L., Babiarte, S. M. M. (2018). ANTIBACTERIAL EFFECT OF SINAW SINAW (Peperomia pellucida) LEAF EXTRACT ON Staphylococcus aureus.",
    abstract: "Tested various concentrations. Results showed that 100% pure Sinaw sinaw leaf extract is the most effective antibacterial treatment against Staphylococcus aureus.",
  },
  {
    title: "ANTI-ANGIOGENIC ACTIVITY OF CALABASH (Crescentia cujete) LEAF EXTRACT",
    publishedAt: 2018,
    researchId: "2018-018",
    author: "FRANCIS MATHEW M. GAPPE, MARVIN B. MALIFICIAR, CAMELLA BEATRICE L. VALLE",
    citation: "Gappe, F. M. M., Malificiar, M. B., Valle, C. B. L. (2018). ANTI-ANGIOGENIC ACTIVITY OF CALABASH (Crescentia cujete) LEAF EXTRACT.",
    abstract: "Used in ovo (Anas platyrhynchos) CAM assay. Results revealed Calabash leaf extract exhibits anti-angiogenic activity significantly different from the negative control.",
  },
  {
    title: "ANTIMICROBIAL EFFECT OF PARAGIS (Eleusine indica Linn.) GRASS EXTRACT ON UTI-CAUSING BACTERIA",
    publishedAt: 2018,
    researchId: "2018-019",
    author: "SEAN ANJELO C. HALABA, CIARA MARIE C. BERNARDO, JEAN RAY D. REYES",
    citation: "Halaba, S. A. C., Bernardo, C. M. C., Reyes, J. R. D. (2018). ANTIMICROBIAL EFFECT OF PARAGIS (Eleusine indica Linn.) GRASS EXTRACT ON UTI-CAUSING BACTERIA.",
    abstract: "Paragis grass was extracted using a juicer. Results showed that the grass extract had no antimicrobial effect on Escherichia coli in terms of zone of inhibition.",
  },
  {
    title: "CYTOTOXICITY AND ANTI-ANGIOGENIC ACTIVITY OF TUBLI (Derris elliptica Benth.) LEAF EXTRACT",
    publishedAt: 2018,
    researchId: "2018-020",
    author: "ROMNICK A. SULIT, JESSA G. ALEMANI NOVIE, JENDEL M. SALIGANAN",
    citation: "Sulit, R. A., Novie, J. G. A., Saliganan, J. M. (2018). CYTOTOXICITY AND ANTI-ANGIOGENIC ACTIVITY OF TUBLI (Derris elliptica Benth.) LEAF EXTRACT.",
    abstract: "Determined LC50 for Tubli leaf extract (160.349 g/mL), showing significant cytotoxic activity. 200 and 300 ppm treatments showed significant anti-angiogenic activity.",
  },
  {
    title: "EFFECTIVENESS OF PAPAYA (Carica papaya Linn.) LEAF EXTRACT AS A BLOOD COAGULANT",
    publishedAt: 2018,
    researchId: "2018-021",
    author: "CARL ANDRAE A. JULIANO, RHYZA C. PASADILLA, JHUN CARL N. PANIZA",
    citation: "Juliano, C. A. A., Pasadilla, R. C., Paniza, J. C. N. (2018). EFFECTIVENESS OF PAPAYA (Carica papaya Linn.) LEAF EXTRACT AS A BLOOD COAGULANT.",
    abstract: "Tested on human blood types A, B, AB, and O. It was concluded that papaya leaf extract is not effective as a general blood coagulant across all types tested.",
  },
  {
    title: "PESTICIDAL EFFECT OF HAGONOY (Chromolaena odorata) IN MOSQUITO (Culicidae)",
    publishedAt: 2018,
    researchId: "2018-022",
    author: "KIMBERLY E. LLADO, JOHN RENZ P. HEREZO",
    citation: "Llado, K. E., Herezo, J. R. P. (2018). PESTICIDAL EFFECT OF HAGONOY (Chromolaena odorata) IN MOSQUITO (Culicidae).",
    abstract: "Pesticide made by pounding Hagonoy and squeezing extract. Based on results, the extract can be used as a safer pesticide to kill mosquitoes.",
  },
  {
    title: "LARVICIDAL ACTIVITY OF KAYOS (Dioscorea hispida) LEAF EXTRACT ON MOSQUITO WRIGGLERS",
    publishedAt: 2018,
    researchId: "2018-023",
    author: "JUDY M. SUBANG, ARNIE GRACE Q. MORENO",
    citation: "Subang, J. M., Moreno, A. G. Q. (2018). LARVICIDAL ACTIVITY OF KAYOS (Dioscorea hispida) LEAF EXTRACT ON MOSQUITO WRIGGLERS.",
    abstract: "Ethanolic extract tested against wrigglers. Results showed 1000 ppm extract significantly affected mortality, with an LC50 of 1055.513 ppm after 48 hours.",
  },
  {
    title: "POWDERED TALABA (Crossastrea gigas) SHELL AS A COMPONENT IN MAKING CANDLES",
    publishedAt: 2018,
    researchId: "2018-024",
    author: "KENNETH A. TIONGSON, SHENNA I. SOBRETODO, LILIBEN JOHN C. VERA",
    citation: "Tiongson, K. A., Sobretodo, S. I., Vera, L. J. C. (2018). POWDERED TALABA (Crossastrea gigas) SHELL AS A COMPONENT IN MAKING CANDLES.",
    abstract: "Tested powdered shell mixed with wax. Results revealed the addition of powdered Talaba shell has no significant effect on how long the candle lasts.",
  },
  {
    title: "EFFECTIVENESS OF DALANGHITA, LEMONGRASS AND OREGANO AS INSECTICIDAL SPRAY ON TERMITES",
    publishedAt: 2018,
    researchId: "2018-025",
    author: "ELLA SALADAR, PRINCESS GELIN, MAEGAN VALERIE GENIT",
    citation: "Saladar, E., Gelin, P., Genit, M. V. (2018). EFFECTIVENESS OF DALANGHITA, LEMONGRASS AND OREGANO AS INSECTICIDAL SPRAY ON TERMITES.",
    abstract: "Results revealed Dalanghita peel, Lemongrass, and Oregano leaf extracts have the same significant insecticidal effect against Dampwood termites.",
  },
  {
    title: "ISOLATION AND IDENTIFICATION OF AIRBORNE BACTERIA AROUND AND WITHIN THE LANDFILL",
    publishedAt: 2018,
    researchId: "2018-026",
    author: "COLLEEN KATE D. LICERA, CHENNIE M. PASTRANA, ROMELA MARIE P. MANATE",
    citation: "Licera, C. K. D., Pastrana, C. M., Manate, R. M. P. (2018). ISOLATION AND IDENTIFICATION OF AIRBORNE BACTERIA AROUND AND WITHIN THE LANDFILL.",
    abstract: "Airborne bacteria isolated from Brgy. Inaladan landfill include E. faecalis, E. coli, E. aerogenes, K. pneumonieae, and Staphylococcus aureus.",
  },
  {
    title: "QUALITATIVE COLOR CHANGE ASSESSMENT OF BANANA BLOSSOM BRACTS PIGMENT AS PH INDICATORS",
    publishedAt: 2018,
    researchId: "2018-027",
    author: "ATHENA BEATRICE R. ABORDO, FREDDIRICK ERL B. PLAMIANO",
    citation: "Abordo, A. B. R., Plamiano, F. E. B. (2018). QUALITATIVE COLOR CHANGE ASSESSMENT OF BANANA BLOSSOM BRACTS PIGMENT AS PH INDICATORS.",
    abstract: "Banana blossom can be a source of pigment for pH paper and liquid indicators, showing versatility in detecting pH levels in commercial solutions.",
  },
  {
    title: "THE BIODEGRADABILITY OF RIPE SABA BANANA FRUIT PEELINGS TREATED WITH HYDROCHLORIC ACID",
    publishedAt: 2018,
    researchId: "2018-028",
    author: "CHARLENE B. NIEBLA, THERESE MARIE B. GABASA",
    citation: "Niebla, C. B., Gabasa, T. M. B. (2018). THE BIODEGRADABILITY OF RIPE SABA BANANA FRUIT PEELINGS TREATED WITH HYDROCHLORIC ACID.",
    abstract: "Tested various concentrations of HCI. Results showed that the higher the concentration of HCI, the faster the banana peels degrade into bioplastic.",
  },
  {
    title: "ANTI-OXIDATIVE PROPERTY OF TALISAY (Terminalia catappa) LEAF EXTRACT",
    publishedAt: 2018,
    researchId: "2018-029",
    author: "RECHEL MAE P. SUBADE, ALLIAH KAY V. MENDOZA, JONA ANN C. CAMIN",
    citation: "Subade, R. M. P., Mendoza, A. K., Camin, J. A. C. (2018). ANTI-OXIDATIVE PROPERTY OF TALISAY (Terminalia catappa) LEAF EXTRACT.",
    abstract: "The DPPH radical scavenging method was used. Methanolic extracts of Talisay leaves showed a high anti-oxidative property (DPPH scavenging effect).",
  }
];
