import type { ResearchSeedEntry } from "./types";

export const researchData2024: ResearchSeedEntry[] = [
  {
    title: "ALLELOPATHIC ACTIVITY OF JACKFRUIT (Artocarpus heterophyllus) LEAF EXTRACT ON PECHAY (BRASSICA RAPA SUBSP. CHINENSIS)",
    publishedAt: 2024,
    researchId: "2024-001",
    author: "PAUL FEBRIEL D. ADOLFO, ALDRIENE NICOLE S. CARTERA, JULIE ANNE M. ALOC, MARY JUN M. BERONA, REY ANN JOY B. CUSTODIO, GLICIE JOY ANNE B. LAGUARDIA, JANEANE LOUISE A. VELONERO",
    citation: "Adolfo, P. F. D., Cartera, A. N. S., Aloc, J. A. M., Berona, M. J. M., Custodio, R. A. J. B., Laguardia, G. J. A. B., Velonero, J. L. A. (2024). ALLELOPATHIC ACTIVITY OF JACKFRUIT (Artocarpus heterophyllus) LEAF EXTRACT ON PECHAY (BRASSICA RAPA SUBSP. CHINENSIS).",
    abstract: "\n      Allelopathy occurs when one plant species releases phytochemicals that hinder the germination of a plant (GreeksForGeeks, 2020). This study aimed to determine the allelopathic activity of Jackfruit (Artocarpus heterophyllus) leaf extract on Pechay (Brassica rapa subsp. chinensis). The matured leaves of Jackfruit were oven-dried and extracted through a Maceration process. The Pechay seeds were purchased in the market. The experimental treatments that were used are 0.10g/ml (Treatment A), 0.15g/ml (Treatment B), 0.20g/ml (Treatment C), and the Water (Treatment D) control variable. Each seed box was planted with 4 pechay seeds.\n    \n      The Pechay seeds were watered every day early in the morning and late in the afternoon. The pechay seedlings were transferred to a bigger pot after 2 weeks and results were gathered after 23 days of consistent watering using a ruler to measure the plant height in centimeters. As for the number of leaves, the researchers counted the leaves of each pechay seed that germinated and then divided it into 4. To measure its efficacy, the researchers used statistical tools using Mean, Standard Deviation, One-Way ANOVA, and Scheffe. Treatment B (0.15g/ml) of Jackfruit (Artocarpus heterophyllus) leaf extract has the highest allelopathic properties among the experimental treatments. A significant difference was recorded in both number of leaves and plant height.\n    \n      It was proven that Jackfruit (Artocarpus heterophyllus) possesses allelopathic activity. The researchers would like to recommend conducting the study on different plant species to explore the potential use of Jackfruit (Artocarpus heterophyllus).\n    ",
    researchId: "2024-001",
    author: "PAUL FEBRIEL D. ADOLFO, ALDRIENE NICOLE S. CARTERA, JULIE ANNE M. ALOC, MARY JUN M. BERONA, REY ANN JOY B. CUSTODIO, GLICIE JOY ANNE B. LAGUARDIA, JANEANE LOUISE A. VELONERO",
    citation: "Adolfo, P. F. D., Cartera, A. N. S., Aloc, J. A. M., Berona, M. J. M., Custodio, R. A. J. B., Laguardia, G. J. A. B., Velonero, J. L. A. (2024). ALLELOPATHIC ACTIVITY OF JACKFRUIT (Artocarpus heterophyllus) LEAF EXTRACT ON PECHAY (BRASSICA RAPA SUBSP. CHINENSIS).",
    abstract: "This study aimed to determine the allelopathic activity of Jackfruit leaf extract on Pechay. Results revealed that Treatment B (0.15g/ml) had the highest allelopathic properties, showing a significant difference in both number of leaves and plant height.",
    author:
      "PAUL FEBRIEL D. ADOLFO, ALDRIENE NICOLE S. CARTERA, JULIE ANNE M. ALOC, MARY JUN M. BERONA, REY ANN JOY B. CUSTODIO, GLICIE JOY ANNE B. LAGUARDIA, JANEANE LOUISE A. VELONERO",
    abstract:`
      Allelopathy occurs when one plant species releases phytochemicals that hinder the germination of a plant (GreeksForGeeks, 2020). This study aimed to determine the allelopathic activity of Jackfruit (Artocarpus heterophyllus) leaf extract on Pechay (Brassica rapa subsp. chinensis). The matured leaves of Jackfruit were oven-dried and extracted through a Maceration process. The Pechay seeds were purchased in the market. The experimental treatments that were used are 0.10g/ml (Treatment A), 0.15g/ml (Treatment B), 0.20g/ml (Treatment C), and the Water (Treatment D) control variable. Each seed box was planted with 4 pechay seeds.
    
      The Pechay seeds were watered every day early in the morning and late in the afternoon. The pechay seedlings were transferred to a bigger pot after 2 weeks and results were gathered after 23 days of consistent watering using a ruler to measure the plant height in centimeters. As for the number of leaves, the researchers counted the leaves of each pechay seed that germinated and then divided it into 4. To measure its efficacy, the researchers used statistical tools using Mean, Standard Deviation, One-Way ANOVA, and Scheffe. Treatment B (0.15g/ml) of Jackfruit (Artocarpus heterophyllus) leaf extract has the highest allelopathic properties among the experimental treatments. A significant difference was recorded in both number of leaves and plant height.
    
      It was proven that Jackfruit (Artocarpus heterophyllus) possesses allelopathic activity. The researchers would like to recommend conducting the study on different plant species to explore the potential use of Jackfruit (Artocarpus heterophyllus).
    `,
  },
  {
    title: "Laurus nobilis (BAY LEAF) ESSENTIAL OIL ON GUAR GUM-BASED EDIBLE COATING: ITS EFFECT ON THE INHIBITION OF YEAST AND MOLD GROWTH ON Solanum lycopersicum (TOMATO)",
    publishedAt: 2024,
    researchId: "2024-002",
    author: "DULAY, JAY PHILIP B., AQUINO, CHAD COLEEN MCKAY M., CUARTE, KRYSIA P., LORILLA, QUEENY ZYRA C, OLLOSA, KENNIE G, PEDROLA, STACIE DENISE H., ZAPANTA, SOFIA CLAIRE S.",
    citation: "Dulay, J. P. B., Aquino, C. C. M. M., Cuarte, K. P., Lorilla, Q. Z. C., Ollosa, K. G., Pedrola, S. D. H., Zapanta, S. C. S. (2024). Laurus nobilis (BAY LEAF) ESSENTIAL OIL ON GUAR GUM-BASED EDIBLE COATING: ITS EFFECT ON THE INHIBITION OF YEAST AND MOLD GROWTH ON Solanum lycopersicum (TOMATO).",
    abstract: "\n      Tomato (Solanum lycopersicum) has a tendency to be overproduced and has a relatively short post-harvest shelf life. The main factors affecting tomato post-harvest shelf life are yeast and mold infections. Edible coatings like Guar Gum have been explored as an alternative to prolong shelf life of fresh fruits and vegetables. Laurus nobilis leaf essential oil is proven to possess strong antimicrobial and antioxidative properties. The addition of L. nobilis leaf essential oil on Guar Gum-based edible coating could help solve its lack of antifungal properties.\n    \n      This study aimed to determine the effect of the addition of L. nobilis leaf essential oil on Guar Gum-based edible coating on the inhibition of yeast and mold growth on S. lycopersicum. The treatments that were used are Guar Gum supplemented with L. nobilis leaf essential oil (T¹), Guar Gum only (T²) and No coating (T³). Randomized Complete Block Design (RCBD) was used as the experimental layout. The Guar Gum solution was prepared by adding 15 grams of Guar Gum powder in 1000 mL of distilled water. The Guar Gum solution was used for T¹ and T². Five mL of  L. nobilis leaf essential oil was added on T¹. The tomatoes were dipped in each treatment with the exception of those in T³. The tomatoes were then left to dry in a cool and dry place to be subjected to the microbial growth assay after 18 days. Visible colonies were counted and Colony Forming Units/mL was calculated and analyzed using ANOVA in Microsoft Excel.\n    \n      The results revealed that yeast and mold growth on all treatments are comparable with each other. The researchers recommend to extract and explore other essential oils that may possess strong anti-fungal properties in various concentrations to be added to the Guar Gum solution and test its efficacy on the inhibition of yeast and mold growth on other fruits and vegetables.\n    ",
    researchId: "2024-002",
    author: "DULAY, JAY PHILIP B., AQUINO, CHAD COLEEN MCKAY M., CUARTE, KRYSIA P., LORILLA, QUEENY ZYRA C, OLLOSA, KENNIE G, PEDROLA, STACIE DENISE H., ZAPANTA, SOFIA CLAIRE S.",
    citation: "Dulay, J. P. B., Aquino, C. C. M. M., Cuarte, K. P., Lorilla, Q. Z. C., Ollosa, K. G., Pedrola, S. D. H., Zapanta, S. C. S. (2024). Laurus nobilis (BAY LEAF) ESSENTIAL OIL ON GUAR GUM-BASED EDIBLE COATING: ITS EFFECT ON THE INHIBITION OF YEAST AND MOLD GROWTH ON Solanum lycopersicum (TOMATO).",
    abstract: "This study investigated the addition of Bay Leaf essential oil to Guar Gum-based edible coatings to inhibit yeast and mold on tomatoes. Results showed that microbial growth across all treatments was comparable, though the oil is known for antimicrobial properties.",
    author:
      "DULAY, JAY PHILIP B., AQUINO, CHAD COLEEN MCKAY M., CUARTE, KRYSIA P., LORILLA, QUEENY ZYRA C, OLLOSA, KENNIE G, PEDROLA, STACIE DENISE H., ZAPANTA, SOFIA CLAIRE S.",
    abstract:`
      Tomato (Solanum lycopersicum) has a tendency to be overproduced and has a relatively short post-harvest shelf life. The main factors affecting tomato post-harvest shelf life are yeast and mold infections. Edible coatings like Guar Gum have been explored as an alternative to prolong shelf life of fresh fruits and vegetables. Laurus nobilis leaf essential oil is proven to possess strong antimicrobial and antioxidative properties. The addition of L. nobilis leaf essential oil on Guar Gum-based edible coating could help solve its lack of antifungal properties.
    
      This study aimed to determine the effect of the addition of L. nobilis leaf essential oil on Guar Gum-based edible coating on the inhibition of yeast and mold growth on S. lycopersicum. The treatments that were used are Guar Gum supplemented with L. nobilis leaf essential oil (T¹), Guar Gum only (T²) and No coating (T³). Randomized Complete Block Design (RCBD) was used as the experimental layout. The Guar Gum solution was prepared by adding 15 grams of Guar Gum powder in 1000 mL of distilled water. The Guar Gum solution was used for T¹ and T². Five mL of  L. nobilis leaf essential oil was added on T¹. The tomatoes were dipped in each treatment with the exception of those in T³. The tomatoes were then left to dry in a cool and dry place to be subjected to the microbial growth assay after 18 days. Visible colonies were counted and Colony Forming Units/mL was calculated and analyzed using ANOVA in Microsoft Excel.
    
      The results revealed that yeast and mold growth on all treatments are comparable with each other. The researchers recommend to extract and explore other essential oils that may possess strong anti-fungal properties in various concentrations to be added to the Guar Gum solution and test its efficacy on the inhibition of yeast and mold growth on other fruits and vegetables.
    `,
  },
  {
    title: "EVALUATION OF THE ANTIPYRETIC EFFECT OF Arcangelisia flava (ALBUTRA) STEM EXTRACT ON Rattus novergicus domesticus (NORWEIGIAN BLACK-HOODED DOMESTICATED RAT)",
    publishedAt: 2024,
    researchId: "2024-003",
    author: "THEO RUCEL C. PRIETO, KYLA JANE C. BILLOSO, ALAIZA C. CONLACION, MARJOLENE J. GALINDO, KERK JUSTINE G. GUIJARNO, MYKAELLA XZY R. PANIAGUA, GWYNETH A. SETERA",
    citation: "Prieto, T. R. C., Billoso, K. J. C., Conlacion, A. C., Galindo, M. J., Guijarno, K. J. G., Paniagua, M. X. R., Setera, G. A. (2024). EVALUATION OF THE ANTIPYRETIC EFFECT OF Arcangelisia flava (ALBUTRA) STEM EXTRACT ON Rattus novergicus domesticus (NORWEIGIAN BLACK-HOODED DOMESTICATED RAT).",
    abstract: "\n      Fever, characterized by an elevated body temperature, is a common symptom associated with various physiological and pathological conditions. Natural remedies derived from medicinal plants have been explored as potential sources for antipyretic agents.\n    \n    \n      This study aimed to determine the antipyretic activity of Arcangelisa flava (Albutra) stem extracts on Rattus novergicus domesticus (Norweigian Black-Hooded Domesticated Rat). The Albutra stems were extracted using the ethanolic extraction and maceration method. The Norwegian Black-Hooded Domesticated Rats were purchased in a pet store; all aged between 8-12 weeks old. The treatments that were used are 250mg/kg Arcangelisia flava stem extract (Treatment A), 500mg/kg Arcangelisia flava stem extract (Treatment B), Blank control 10ml/kg normal saline vehicle group (Treatment C), and Negative control no application (Treatment D). The rats are divided into four groups; fever was induced in all rats by subcutaneous injection of 15% w/v yeast (Saccharomyces cerevisiae) extract powder suspension. Only rats with a temperature increase of at least 0.5° C after yeast injection were used in the study. The data were collected through observation of the changes in temperature of pyrexia-induced rats after 3 hours for each treatment.\n      \n      The results revealed that the antipyretic activity of 500mg/kg Arcangelisia flava stem extract (Treatment B) had the highest mean decrease followed by 250mg/kg Arcangelisia flava stem extract (Treatment A). However, both treatments were not significantly different from the Blank control 10ml/kg normal saline (Treatment C), and Negative control no application (Treatment D). The researchers recommend that further studies be conducted to test the antipyretic activity of the different parts of the Arcangelisia flava plant such as roots and leaves and utilizing other extraction methods that can enhance the potential antipyretic activity of the plant.\n      ",
    researchId: "2024-003",
    author: "THEO RUCEL C. PRIETO, KYLA JANE C. BILLOSO, ALAIZA C. CONLACION, MARJOLENE J. GALINDO, KERK JUSTINE G. GUIJARNO, MYKAELLA XZY R. PANIAGUA, GWYNETH A. SETERA",
    citation: "Prieto, T. R. C., Billoso, K. J. C., Conlacion, A. C., Galindo, M. J., Guijarno, K. J. G., Paniagua, M. X. R., Setera, G. A. (2024). EVALUATION OF THE ANTIPYRETIC EFFECT OF Arcangelisia flava (ALBUTRA) STEM EXTRACT ON Rattus novergicus domesticus (NORWEIGIAN BLACK-HOODED DOMESTICATED RAT).",
    abstract: "Determined the antipyretic activity of Albutra stem extracts on rats. Treatment with 500mg/kg extract showed the highest mean decrease in temperature, although the results were not significantly different from the control groups.",
    author:
      "THEO RUCEL C. PRIETO, KYLA JANE C. BILLOSO, ALAIZA C. CONLACION, MARJOLENE J. GALINDO, KERK JUSTINE G. GUIJARNO, MYKAELLA XZY R. PANIAGUA, GWYNETH A. SETERA",
    abstract:`
      Fever, characterized by an elevated body temperature, is a common symptom associated with various physiological and pathological conditions. Natural remedies derived from medicinal plants have been explored as potential sources for antipyretic agents.
    
    
      This study aimed to determine the antipyretic activity of Arcangelisa flava (Albutra) stem extracts on Rattus novergicus domesticus (Norweigian Black-Hooded Domesticated Rat). The Albutra stems were extracted using the ethanolic extraction and maceration method. The Norwegian Black-Hooded Domesticated Rats were purchased in a pet store; all aged between 8-12 weeks old. The treatments that were used are 250mg/kg Arcangelisia flava stem extract (Treatment A), 500mg/kg Arcangelisia flava stem extract (Treatment B), Blank control 10ml/kg normal saline vehicle group (Treatment C), and Negative control no application (Treatment D). The rats are divided into four groups; fever was induced in all rats by subcutaneous injection of 15% w/v yeast (Saccharomyces cerevisiae) extract powder suspension. Only rats with a temperature increase of at least 0.5° C after yeast injection were used in the study. The data were collected through observation of the changes in temperature of pyrexia-induced rats after 3 hours for each treatment.
      
      The results revealed that the antipyretic activity of 500mg/kg Arcangelisia flava stem extract (Treatment B) had the highest mean decrease followed by 250mg/kg Arcangelisia flava stem extract (Treatment A). However, both treatments were not significantly different from the Blank control 10ml/kg normal saline (Treatment C), and Negative control no application (Treatment D). The researchers recommend that further studies be conducted to test the antipyretic activity of the different parts of the Arcangelisia flava plant such as roots and leaves and utilizing other extraction methods that can enhance the potential antipyretic activity of the plant.
      `,
  },
  {
    title: "COMPARATIVE ANALYSIS OF ARTIFICIAL NUTRIENT SOLUTION AND Kappaphycus alvarezii (GUSO) EXTRACT IN GROWING OF Lactuca sativa L. (LETTUCE) HYDROPONICALLY",
    publishedAt: 2024,
    researchId: "2024-004",
    author: "MENARD M. MATULLANO, JOEL BRIAN ALCALDE, MIKKA M. ELISEO, ELAINE MAREE M. ESCAÑO, LYCIA REYN S. LOCSIN, CARL JULIUS G. OÑATE, EDELWEISS B. SOMES",
    citation: "Matullano, M. M., Alcalde, J. B., Eliseo, M. M., Escaño, E. M. M., Locsin, L. R. S., Oñate, C. J. G., Somes, E. B. (2024). COMPARATIVE ANALYSIS OF ARTIFICIAL NUTRIENT SOLUTION AND Kappaphycus alvarezii (GUSO) EXTRACT IN GROWING OF Lactuca sativa L. (LETTUCE) HYDROPONICALLY.",
    abstract: "\n      The increasing demand for efficient resource management and high-quality food production had driven the shift towards hydroponics. Various commercial and specialty crops can be grown using hydroponics, among them are leafy vegetables like lettuce.\n    \n      This study compared the efficiency of  Kappaphycus alvarezii extract and Artificial Nutrient Solution in hydroponic farming of Lactuca sativa L. (lettuce). Kappaphycus alvarezii extract was obtained through blending and filtration, while Artificial Nutrient Solution was purchased locally. Lettuce seeds were germinated for 10 days, and then transferred to jars. Treatments included Kappaphycus alvarezii extract (10%)/distilled water (90%) (Treatment A), Artificial Nutrient Solution (Treatment B), and a Negative Control (Treatment C). After 30 days, observations were made on changes in its mass, height, and number of leaves\n    \n      The results revealed that Artificial Nutrient Solution (Treatment B) had the highest mean, followed by Kappaphycus alvarezii extract (Treatment A). Both treatments were not significantly different from each other; however, treatment B showed a significant difference from the Negative Control (Treatment C). The researchers recommend that Kappaphycus alvarezii extract can be used as an alternative to hydroponics farming if there is an abundant amount of resources present within the community.\n    ",
    researchId: "2024-004",
    author: "MENARD M. MATULLANO, JOEL BRIAN ALCALDE, MIKKA M. ELISEO, ELAINE MAREE M. ESCAÑO, LYCIA REYN S. LOCSIN, CARL JULIUS G. OÑATE, EDELWEISS B. SOMES",
    citation: "Matullano, M. M., Alcalde, J. B., Eliseo, M. M., Escaño, E. M. M., Locsin, L. R. S., Oñate, C. J. G., Somes, E. B. (2024). COMPARATIVE ANALYSIS OF ARTIFICIAL NUTRIENT SOLUTION AND Kappaphycus alvarezii (GUSO) EXTRACT IN GROWING OF Lactuca sativa L. (LETTUCE) HYDROPONICALLY.",
    abstract: "Compared Guso extract and artificial nutrient solution in hydroponic lettuce farming. While the artificial solution had the highest mean growth, Guso extract showed potential as a viable organic alternative.",
    author:
      "MENARD M. MATULLANO, JOEL BRIAN ALCALDE, MIKKA M. ELISEO, ELAINE MAREE M. ESCAÑO, LYCIA REYN S. LOCSIN, CARL JULIUS G. OÑATE, EDELWEISS B. SOMES",
    abstract:`
      The increasing demand for efficient resource management and high-quality food production had driven the shift towards hydroponics. Various commercial and specialty crops can be grown using hydroponics, among them are leafy vegetables like lettuce.
    
      This study compared the efficiency of  Kappaphycus alvarezii extract and Artificial Nutrient Solution in hydroponic farming of Lactuca sativa L. (lettuce). Kappaphycus alvarezii extract was obtained through blending and filtration, while Artificial Nutrient Solution was purchased locally. Lettuce seeds were germinated for 10 days, and then transferred to jars. Treatments included Kappaphycus alvarezii extract (10%)/distilled water (90%) (Treatment A), Artificial Nutrient Solution (Treatment B), and a Negative Control (Treatment C). After 30 days, observations were made on changes in its mass, height, and number of leaves
    
      The results revealed that Artificial Nutrient Solution (Treatment B) had the highest mean, followed by Kappaphycus alvarezii extract (Treatment A). Both treatments were not significantly different from each other; however, treatment B showed a significant difference from the Negative Control (Treatment C). The researchers recommend that Kappaphycus alvarezii extract can be used as an alternative to hydroponics farming if there is an abundant amount of resources present within the community.
    `,
  },
  {
    title: "SHELF-LIFE ENHANCEMENT OF Carica papaya USING ZINC OXIDE AS NANOPARTICLES",
    publishedAt: 2024,
    researchId: "2024-005",
    author: "LAMPARERO, JAPETH M., CHICHIRITA, ELLA CARYLLE FAYE E., DY, TRINA MARIE C., ESTREVILLO, MARY HOPE C., MANA-AY, TRISIA CLAIRE P., MASIADO, CHRISTINE JOY N., MONTEFRIO, ANGELICA MARIE M.",
    citation: "Lamparero, J. M., Chichirita, E. C. F. E., Dy, T. M. C., Estrevillo, M. H. C., Mana-Ay, T. C. P., Masiado, C. J. N., Montefrio, A. M. M. (2024). SHELF-LIFE ENHANCEMENT OF Carica papaya USING ZINC OXIDE AS NANOPARTICLES.",
    abstract: "\n    The rapid ripening of locally grown Carica papaya is a problem in the quality of production. However, fruit ripening of papaya has been genetically modified to extend its shelf life (Geetika et al., 2018). This study was designed to determine the effect of Zinc oxide as a nanoparticle in shelf-life enhancement of Carica papaya in terms of mass (g) loss.\n    \n    The synthesis of Zinc oxide started with a zinc precursor composed of 132 g of zinc acetate dihydrate, being dissolved into a 1 500 ml of ethanol. The powdery residue of Zinc Oxide that was produced were dissolved into ethanol according to different treatments. Thirty-six almost ripe Carica papaya were assigned into four treatments: Treatment 1 (25%), Treatment 2 (50%), Treatment 3 (75%), and Treatment 4 (Negative Control). The synthesis of Zinc oxide duration was five days and the observation of Carica papaya was ten days. Mean and Anova were used to analyze the data.\n    \n    Results revealed that among the treatments, Treatment 4 is significantly effective than Treatment 1, Treatment 2, and Treatment 3. However, Treatment 1 (25%) showed lower mass (g) loss than the rest of the experimental treatments. The application of Zinc oxide showed positive effects on enhancing the shelf-life of Carica papaya in terms of mass (g) loss but less effective than the negative control (distilled water). The researchers conclude that Zinc oxide as Nanoparticles has no significant effect in shelf-life enhancement of Carica Papaya in terms of mass (g) loss. There is no significant difference in the Shelf Enhancement of the different concentration of Zinc Oxide as nanoparticles ten days after the application treatments.\n    ",
    researchId: "2024-005",
    author: "JAPETH M. LAMPARERO, ELLA CARYLLE FAYE E. CHICHIRITA, TRINA MARIE C. DY, MARY HOPE C. ESTREVILLO, TRISIA CLAIRE P. MANAAY, CHRISTINE JOY N. MASIADO, ANGELICA MARIE M. MONTEFRIO",
    citation: "Lamparero, J. M., Chichirita, E. C. F. E., Dy, T. M. C., Estrevillo, M. H. C., Mana-Ay, T. C. P., Masiado, C. J. N., Montefrio, A. M. M. (2024). SHELF-LIFE ENHANCEMENT OF Carica papaya USING ZINC OXIDE AS NANOPARTICLES.",
    abstract: "Designed to determine the effect of Zinc Oxide nanoparticles on the shelf-life of papaya. Results indicated that while some concentrations slowed mass loss, there was no significant difference compared to the negative control.",
    author:
      "JAPETH M. LAMPARERO, ELLA CARYLLE FAYE E. CHICHIRITA, TRINA MARIE C. DY, MARY HOPE C. ESTREVILLO, TRISIA CLAIRE P. MANAAY, CHRISTINE JOY N. MASIADO, ANGELICA MARIE M. MONTEFRIO",
    abstract:`
    The rapid ripening of locally grown Carica papaya is a problem in the quality of production. However, fruit ripening of papaya has been genetically modified to extend its shelf life (Geetika et al., 2018). This study was designed to determine the effect of Zinc oxide as a nanoparticle in shelf-life enhancement of Carica papaya in terms of mass (g) loss.
    
    The synthesis of Zinc oxide started with a zinc precursor composed of 132 g of zinc acetate dihydrate, being dissolved into a 1 500 ml of ethanol. The powdery residue of Zinc Oxide that was produced were dissolved into ethanol according to different treatments. Thirty-six almost ripe Carica papaya were assigned into four treatments: Treatment 1 (25%), Treatment 2 (50%), Treatment 3 (75%), and Treatment 4 (Negative Control). The synthesis of Zinc oxide duration was five days and the observation of Carica papaya was ten days. Mean and Anova were used to analyze the data.
    
    Results revealed that among the treatments, Treatment 4 is significantly effective than Treatment 1, Treatment 2, and Treatment 3. However, Treatment 1 (25%) showed lower mass (g) loss than the rest of the experimental treatments. The application of Zinc oxide showed positive effects on enhancing the shelf-life of Carica papaya in terms of mass (g) loss but less effective than the negative control (distilled water). The researchers conclude that Zinc oxide as Nanoparticles has no significant effect in shelf-life enhancement of Carica Papaya in terms of mass (g) loss. There is no significant difference in the Shelf Enhancement of the different concentration of Zinc Oxide as nanoparticles ten days after the application treatments.
    `,
  },
  {
    title: "A COMPARATIVE ANALYSIS ON THE EFFECTIVITY OF SABA BANANA (Musa acuminata x balbisiana) PEELS AND SUGARCANE (Saccharum officinarum) PEELS AS ALTERNATIVE FEEDS FOR AFRICAN CATFISH (Clarias gariepinus)",
    publishedAt: 2024,
    researchId: "2024-006",
    author: "CAYABYAB, PRANCE NATHANIEL, DARADAR, LOUIE JOHN, ESCANDA, ACESHELLE MARIE, MEDIANESTA, ANN MONIQUE, MENDOZA, GLORIA ELIZABETH, SERVITA, PRILENE, VELASCO, JARA KEZIAH",
    citation: "Cayabyab, P. N., Daradar, L. J., Escanda, A. M., Medianesta, A. M., Mendoza, G. E., Servita, P., Velasco, J. K. (2024). A COMPARATIVE ANALYSIS ON THE EFFECTIVITY OF SABA BANANA (Musa acuminata x balbisiana) PEELS AND SUGARCANE (Saccharum officinarum) PEELS AS ALTERNATIVE FEEDS FOR AFRICAN CATFISH (Clarias gariepinus).",
    abstract: "\n    \n      Catfish play a major role in economic development and advancement, especially in the aquaculture and food industries. Their rapid growth and adaptability create job opportunities, increase trade both domestically and internationally, encourage travel, and encourage leisure activities.\n      \n      In this study, the effects of Sugarcane (Saccharum officinarum) peels and Saba banana (Musa acuminata x balbisiana) peels on fish growth as well as their efficacy as a catfish diet was examined. Through this comparative investigation, the researchers hope to clarify which feed alternative is best for catfish growing and highlight the possible uses of these leftovers in resolving issues facing the aquaculture sector. The Musa acuminata x balbisiana peels and Saccharum officinarum peels, formulation using pearson square method to 45% crude protein level and ingredients like rice bran and fishmeal. The weighted data after 4 weeks of feeding were statistically analyzed using ANOVA.\n      \n      The results revealed that there is no significant difference between the treatments, the Saba banana (Musa acuminata x balbisiana) peels yielded a greater result in the average weight gain of Catfish (Clarias gariepinus) than Sugarcane (Saccharum officinarum) peels after four weeks of feeding.\n      ",
    researchId: "2024-006",
    author: "PRANCE NATHANIEL CAYABYAB, LOUIE JOHN DARADAR, ACESHELLE MARIE ESCANDA, ANN MONIQUE MEDIANESTA, GLORIA ELIZABETH MENDOZA, PRILENE SERVITA, JARA KEZIAH VELASCO",
    citation: "Cayabyab, P. N., Daradar, L. J., Escanda, A. M., Medianesta, A. M., Mendoza, G. E., Servita, P., Velasco, J. K. (2024). A COMPARATIVE ANALYSIS ON THE EFFECTIVITY OF SABA BANANA (Musa acuminata x balbisiana) PEELS AND SUGARCANE (Saccharum officinarum) PEELS AS ALTERNATIVE FEEDS FOR AFRICAN CATFISH (Clarias gariepinus).",
    abstract: "Examined banana and sugarcane peels as catfish feed. ANOVA showed no significant difference between treatments, but Saba banana peels yielded slightly higher average weight gain in the African catfish.",
    author:
      "PRANCE NATHANIEL CAYABYAB, LOUIE JOHN DARADAR, ACESHELLE MARIE ESCANDA, ANN MONIQUE MEDIANESTA, GLORIA ELIZABETH MENDOZA, PRILENE SERVITA, JARA KEZIAH VELASCO",
    abstract:`
    
      Catfish play a major role in economic development and advancement, especially in the aquaculture and food industries. Their rapid growth and adaptability create job opportunities, increase trade both domestically and internationally, encourage travel, and encourage leisure activities.
      
      In this study, the effects of Sugarcane (Saccharum officinarum) peels and Saba banana (Musa acuminata x balbisiana) peels on fish growth as well as their efficacy as a catfish diet was examined. Through this comparative investigation, the researchers hope to clarify which feed alternative is best for catfish growing and highlight the possible uses of these leftovers in resolving issues facing the aquaculture sector. The Musa acuminata x balbisiana peels and Saccharum officinarum peels, formulation using pearson square method to 45% crude protein level and ingredients like rice bran and fishmeal. The weighted data after 4 weeks of feeding were statistically analyzed using ANOVA.
      
      The results revealed that there is no significant difference between the treatments, the Saba banana (Musa acuminata x balbisiana) peels yielded a greater result in the average weight gain of Catfish (Clarias gariepinus) than Sugarcane (Saccharum officinarum) peels after four weeks of feeding.
      `,
  },
  {
    title: "COMPARATIVE ANALYSIS ON ANTIMITOTIC PROPERTY OF CURCUMA LONGA RHIZOME AND SAMANEA SAMAN LEAF EXTRACT USING ALLIUM CEPA ASSAY",
    publishedAt: 2024,
    researchId: "2024-007",
    author: "SEGURA, EARL JAN L., AMBOY, PAULINE MAE M., FLORES, NICOLE FAYE S., LEYSO, MARY FRANCINE SNOW S., MADALOGDOG, JASMIN ANN A., ROBLES, ZHYRA M., VALENZUELA, KHEA MAE A.",
    citation: "Segura, E. J. L., Amboy, P. M. M., Flores, N. F. S., Leyso, M. F. S. S., Madalogdog, J. A. A., Robles, Z. M., Valenzuela, K. M. A. (2024). COMPARATIVE ANALYSIS ON ANTIMITOTIC PROPERTY OF CURCUMA LONGA RHIZOME AND SAMANEA SAMAN LEAF EXTRACT USING ALLIUM CEPA ASSAY.",
    abstract: "\n      As the third leading cause of death in the Philippines, cancer is a major global public health problem. It's a well-known disease that may start practically anywhere in the body and spread to other organs when unchecked cell development occurs (Saboo et al., 2014). \n    \n      This study aims to determine the antimitotic activity of Curcuma longa rhizome and Samanea saman leaf extract using Allium cepa assay. Curcuma longa rhizomes and Samanea saman leaves were both extracted using ethanol extraction. Rotary evaporation was employed to extract the extract's solvent. In formulating the treatments, 3 grams of plant extract were measured, mixed with 1 milliliter of ethanol and finally mixed with distilled water until it reaches the total amount of 300 mL. The Allium cepa then submerged to each treatment of Curcuma longa rhizome and Samanea saman leaf extract. The change in root length of the onion were measured after 3 days of submerging it to the treatments. The results were statistically analyzed using ANOVA and Scheffe Test.\n    \n      Results revealed that Samanea saman leaf extract is significantly lower than the Curcuma longa rhizomes extract and the negative control. Thus, it was concluded that Samanea saman possesses a more effective antimitotic property than Curcuma longa rhizomes extract and was recommended planting more turmeric (Curcuma longa) and rain tree (Samanea saman) because they can be beneficial to us in such ways, especially their antimitotic properties.\n    ",
    researchId: "2024-007",
    author: "EARL JAN L. SEGURA, PAULINE MAE M. AMBOY, NICOLE FAYE S. FLORES, MARY FRANCINE SNOW S. LEYSO, JASMIN ANN A. MADALOGDOG, ZHYRA M. ROBLES, KHEA MAE A. VALENZUELA",
    citation: "Segura, E. J. L., Amboy, P. M. M., Flores, N. F. S., Leyso, M. F. S. S., Madalogdog, J. A. A., Robles, Z. M., Valenzuela, K. M. A. (2024). COMPARATIVE ANALYSIS ON ANTIMITOTIC PROPERTY OF CURCUMA LONGA RHIZOME AND SAMANEA SAMAN LEAF EXTRACT USING ALLIUM CEPA ASSAY.",
    abstract: "Investigated antimitotic properties using the Allium cepa (onion) assay. Samanea saman (Rain Tree) leaf extract was found to be significantly more effective in inhibiting root growth compared to Curcuma longa (Turmeric).",
    author:
      "EARL JAN L. SEGURA, PAULINE MAE M. AMBOY, NICOLE FAYE S. FLORES, MARY FRANCINE SNOW S. LEYSO, JASMIN ANN A. MADALOGDOG, ZHYRA M. ROBLES, KHEA MAE A. VALENZUELA",
      As the third leading cause of death in the Philippines, cancer is a major global public health problem. It's a well-known disease that may start practically anywhere in the body and spread to other organs when unchecked cell development occurs (Saboo et al., 2014). 
    
      This study aims to determine the antimitotic activity of Curcuma longa rhizome and Samanea saman leaf extract using Allium cepa assay. Curcuma longa rhizomes and Samanea saman leaves were both extracted using ethanol extraction. Rotary evaporation was employed to extract the extract's solvent. In formulating the treatments, 3 grams of plant extract were measured, mixed with 1 milliliter of ethanol and finally mixed with distilled water until it reaches the total amount of 300 mL. The Allium cepa then submerged to each treatment of Curcuma longa rhizome and Samanea saman leaf extract. The change in root length of the onion were measured after 3 days of submerging it to the treatments. The results were statistically analyzed using ANOVA and Scheffe Test.
    
      Results revealed that Samanea saman leaf extract is significantly lower than the Curcuma longa rhizomes extract and the negative control. Thus, it was concluded that Samanea saman possesses a more effective antimitotic property than Curcuma longa rhizomes extract and was recommended planting more turmeric (Curcuma longa) and rain tree (Samanea saman) because they can be beneficial to us in such ways, especially their antimitotic properties.
    `,
  },
  {
    title: "Antipyretic Potential of Kara-Kamote (Ipomoea triloba) Aqueous Solution to White Mice (Mus musculus)",
    publishedAt: 2024,
    researchId: "2024-008",
    author: "BORDON, FINNYROSE BERNADETTE B., BRILLO, JEO V., CABARLES, RAINNIER BENEDICT E., DOMINGUEZ, ARNEL ROSS FRANCIS A., MALCONTENTO, HANS CHRISTIAN M., PAGUIDIAN, ANGELA KRISTEN C., PIZ, FRENCH ALDRIN E., SANTISO, ANTHONY JOSH G.",
    citation: "Bordon, F. B. B., Brillo, J., Cabarles, R. B. E., Dominguez, A. R. F. A., Malcontento, H. C. M., Paguidian, A. K. C., Piz, F. A. E., Santiso, A. J. G. (2024). Antipyretic Potential of Kara-Kamote (Ipomoea triloba) Aqueous Solution to White Mice (Mus musculus).",
    abstract: "\n      Fever is also known as hyperthermia, pyrexia, or elevated temperature. It describes a body temperature that's higher than normal. Fever can affect children and adults. Natural remedies derived from medicinal plants have been explored as potential sources of antipyretic agents.\n    \n    \n      This study aimed to determine the antipyretic potential of Kara-kamote (Ipomoea triloba) aqueous solution on white mice (Mus musculus). The Kara-kamote (Ipomoea triloba) aqueous solution was prepared by air-drying the leaves for seven days and was pulverized. After that it was soaked in the distilled water (1:20 m/v) for 72h. The white mice were purchased in a pet store; all aged between 8-12 weeks old. The treatments were Treatment A (50mg/kg), Treatment B (100mg/kg) and Treatment C (No Application). Fever were induced in all mice by subcutaneous injection of a yeast (Saccharomyces cerevisiae) extract powder suspension. Only mice with a temperature increase of at least 0.5° C after yeast injection. The data were collected through observation of the changes in temperature of pyrexia-induced white mice after three hours for each treatment.\n                  \n    \n      The results revealed that the antipyretic activity of Treatment B (100mg/kg) had the highest mean decrease followed by Treatment A (50mg/kg). However, both treatments were not significantly different to the Treatment C (Negative Control). The researchers recommend that further studies be conducted in order to test the antipyretic activity of Kara-kamote (Ipomoea triloba).\n    ",
    researchId: "2024-008",
    author: "FINNYROSE BERNADETTE B. BORDON, JEO V. BRILLO, RAINNIER BENEDICT E. CABARLES, ARNEL ROSS FRANCIS A. DOMINGUEZ, HANS CHRISTIAN M. MALCONTENTO, ANGELA KRISTEN C. PAGUIDIAN, FRENCH ALDRIN E. PIZ, ANTHONY JOSH G. SANTISO",
    citation: "Bordon, F. B. B., Brillo, J., Cabarles, R. B. E., Dominguez, A. R. F. A., Malcontento, H. C. M., Paguidian, A. K. C., Piz, F. A. E., Santiso, A. J. G. (2024). Antipyretic Potential of Kara-Kamote (Ipomoea triloba) Aqueous Solution to White Mice (Mus musculus).",
    abstract: "Tested the antipyretic potential of Kara-kamote aqueous solution on mice. The 100mg/kg concentration showed the highest mean temperature decrease, though statistically comparable to the control group.",
    author:
      "FINNYROSE BERNADETTE B. BORDON, JEO V. BRILLO, RAINNIER BENEDICT E. CABARLES, ARNEL ROSS FRANCIS A. DOMINGUEZ, HANS CHRISTIAN M. MALCONTENTO, ANGELA KRISTEN C. PAGUIDIAN, FRENCH ALDRIN E. PIZ, ANTHONY JOSH G. SANTISO",
    abstract:`
      Fever is also known as hyperthermia, pyrexia, or elevated temperature. It describes a body temperature that's higher than normal. Fever can affect children and adults. Natural remedies derived from medicinal plants have been explored as potential sources of antipyretic agents.
    
    
      This study aimed to determine the antipyretic potential of Kara-kamote (Ipomoea triloba) aqueous solution on white mice (Mus musculus). The Kara-kamote (Ipomoea triloba) aqueous solution was prepared by air-drying the leaves for seven days and was pulverized. After that it was soaked in the distilled water (1:20 m/v) for 72h. The white mice were purchased in a pet store; all aged between 8-12 weeks old. The treatments were Treatment A (50mg/kg), Treatment B (100mg/kg) and Treatment C (No Application). Fever were induced in all mice by subcutaneous injection of a yeast (Saccharomyces cerevisiae) extract powder suspension. Only mice with a temperature increase of at least 0.5° C after yeast injection. The data were collected through observation of the changes in temperature of pyrexia-induced white mice after three hours for each treatment.
                  
    
      The results revealed that the antipyretic activity of Treatment B (100mg/kg) had the highest mean decrease followed by Treatment A (50mg/kg). However, both treatments were not significantly different to the Treatment C (Negative Control). The researchers recommend that further studies be conducted in order to test the antipyretic activity of Kara-kamote (Ipomoea triloba).
    `,
  },
  {
    title: "UTILIZATION OF Vigna unguiculata sesquipedalis BEAN AS FEED RATION SUPPLEMENT FOR Cairina moschata",
    publishedAt: 2024,
    researchId: "2024-009",
    author: "KHYLYN ELORA T. ADOLFO, MARY JOY C. ESTREVILLO, CIARA PRINCESS G. FORTALEZA, ALYSSA MAE M. NUFUAR, RAIZA JANE Y. SARATE, KRYSTINE YANAH L. VICENTE",
    citation: "Adolfo, M. J. C. E. K. E. T., Fortaleza, A. M. M. N. C. P. G., Sarate, K. Y. L. V. R. J. Y. (2024). UTILIZATION OF Vigna unguiculata sesquipedalis BEAN AS FEED RATION SUPPLEMENT FOR Cairina moschata.",
    abstract: "\n      Cairina moschata is one of the products that help with animal production. The Philippines suffers feed quality concerns due to high corn and soya costs, as well as a shortage of nutrients required for ducks. As a result of rising food expenses in the animal production business, researchers are looking at new feed components for cost-effective livestock production. The primary goal of this research is to show that Vigna unguiculata sesquipedalis matured beans may be used as a feed ration supplement in feeds to generate safe and high-quality products while also reducing chicken farming costs. The beans were gathered and sundried according to the procedure employed by Kolu, et al. (2021) and set to different concentrations (+5% and +10%). The growth effects of the treatments on Cairina moschata were assessed using Yibrehu's (2012) approach. The weight increase and FCR of Cairina moschata were measured after the 21st day of treatment application. The data were statistically examined with ANOVA.\n    \n      The results showed that Treatment B has minimal change and is comparable to Treatment A, indicating that it has the potential to be used as a feed ration Supplement for duck growth performance. Thus, it was found that the use of Vigna unguiculata sesquipedalis bean improved the growth performance of ducks (Cairina moschata), although it was less effective than commercial feed growth performance.\n    ",
    researchId: "2024-009",
    author: "KHYLYN ELORA T. ADOLFO, MARY JOY C. ESTREVILLO, CIARA PRINCESS G. FORTALEZA, ALYSSA MAE M. NUFUAR, RAIZA JANE Y. SARATE, KRYSTINE YANAH L. VICENTE",
    citation: "Adolfo, M. J. C. E. K. E. T., Fortaleza, A. M. M. N. C. P. G., Sarate, K. Y. L. V. R. J. Y. (2024). UTILIZATION OF Vigna unguiculata sesquipedalis BEAN AS FEED RATION SUPPLEMENT FOR Cairina moschata.",
    abstract: "Explored using matured beans as feed supplement for ducks. Results showed that the inclusion of the beans improved growth performance and has potential as a cost-effective alternative to commercial feed.",
    author:
      "KHYLYN ELORA T. ADOLFO, MARY JOY C. ESTREVILLO, CIARA PRINCESS G. FORTALEZA, ALYSSA MAE M. NUFUAR, RAIZA JANE Y. SARATE, KRYSTINE YANAH L. VICENTE",
    abstract:`
      Cairina moschata is one of the products that help with animal production. The Philippines suffers feed quality concerns due to high corn and soya costs, as well as a shortage of nutrients required for ducks. As a result of rising food expenses in the animal production business, researchers are looking at new feed components for cost-effective livestock production. The primary goal of this research is to show that Vigna unguiculata sesquipedalis matured beans may be used as a feed ration supplement in feeds to generate safe and high-quality products while also reducing chicken farming costs. The beans were gathered and sundried according to the procedure employed by Kolu, et al. (2021) and set to different concentrations (+5% and +10%). The growth effects of the treatments on Cairina moschata were assessed using Yibrehu's (2012) approach. The weight increase and FCR of Cairina moschata were measured after the 21st day of treatment application. The data were statistically examined with ANOVA.
    
      The results showed that Treatment B has minimal change and is comparable to Treatment A, indicating that it has the potential to be used as a feed ration Supplement for duck growth performance. Thus, it was found that the use of Vigna unguiculata sesquipedalis bean improved the growth performance of ducks (Cairina moschata), although it was less effective than commercial feed growth performance.
    `,
  },
  {
    title: "Marigold (Tagetes erecta) Flower as a Replacement feeds on the Growth of Tilapia fingerlings",
    publishedAt: 2024,
    researchId: "2024-010",
    author: "ASCENCIO, JOHN MARTIN, BIBAL, JESSA MAE G., CALIBJO, ALBERT MATTHEW V., FORRO, FRANZ DAVE R., MADERO, NJ C., MONTUYA, JOHN ZANDER A., PANIZA, GELLOURD L.",
    citation: "Ascencio, J. M., Bibal, J. M. G., Calibjo, A. M., Forro, F. D. R., Madero, N. C., Montuya, J. Z. A., Paniza, G. L. (2024). Marigold (Tagetes erecta) Flower as a Replacement feeds on the Growth of Tilapia fingerlings.",
    abstract: "\n      Inflation caused the commercial feed price to rise and it reduces the profit margin in which can greatly affect local farmers. This study aimed to determine the effect of Marigold flower as a Replacement feed on the growth of Tilapia fingerlings. The Marigold flower was oven dry and finely grind using blendered and pestle and mortar. A total of 180 tilapia fingerlings was utilized and was divided into nine ponds equally. A random sample of five tilapia was weighed weekly. The average weight gain(g) of tilapia fingerlings is analyzed using ANOVA. \n                  \n                  \n      Results revealed that the average weight gain of tilapia fingerlings as affected by different treatments of Marigold flower is not significantly different to that of the commercial feed. In terms of means the different treatment of Marigold flower has a comparative result as that of the commercial feeds.\n\n      Thus, it is concluded that Marigold flower has a potential as a replacement feed on the growth of Tilapia fingerlings.\n    ",
    researchId: "2024-010",
    author: "JOHN MARTIN ASENCIO, JESSA MAE G., CALIBJO, ALBERT MATTHEW V., FORRO, FRANZ DAVE R., MADERO, NJ C., MONTUYA, JOHN ZANDER A., PANIZA, GELLOURD L.",
    citation: "Ascencio, J. M., Bibal, J. M. G., Calibjo, A. M., Forro, F. D. R., Madero, N. C., Montuya, J. Z. A., Paniza, G. L. (2024). Marigold (Tagetes erecta) Flower as a Replacement feeds on the Growth of Tilapia fingerlings.",
    abstract: "Determined the effect of Marigold flower as replacement feed for Tilapia. ANOVA revealed that the weight gain from Marigold treatments was not significantly different from commercial feed, suggesting its potential as a substitute.",
    author:
      "JOHN MARTIN ASENCIO, JESSA MAE G., CALIBJO, ALBERT MATTHEW V., FORRO, FRANZ DAVE R., MADERO, NJ C., MONTUYA, JOHN ZANDER A., PANIZA, GELLOURD L.",
    abstract:`
      Inflation caused the commercial feed price to rise and it reduces the profit margin in which can greatly affect local farmers. This study aimed to determine the effect of Marigold flower as a Replacement feed on the growth of Tilapia fingerlings. The Marigold flower was oven dry and finely grind using blendered and pestle and mortar. A total of 180 tilapia fingerlings was utilized and was divided into nine ponds equally. A random sample of five tilapia was weighed weekly. The average weight gain(g) of tilapia fingerlings is analyzed using ANOVA. 
                  
                  
      Results revealed that the average weight gain of tilapia fingerlings as affected by different treatments of Marigold flower is not significantly different to that of the commercial feed. In terms of means the different treatment of Marigold flower has a comparative result as that of the commercial feeds.

      Thus, it is concluded that Marigold flower has a potential as a replacement feed on the growth of Tilapia fingerlings.
    `,
  },
  {
    title: "Zingiber zerumbet: AN UNDERUTILIZED PLANT AS ORGANIC PESTICIDE AGAINST Drosophila melanogaster",
    publishedAt: 2024,
    researchId: "2024-011",
    author: "CASTOR, ZHEA MARIE C., IBAÑEZ, KAIR IVAN RAE C., INDICAR, KARMELLA A., MANIMBAYAN, JUSTINE M., PADILLA, JESSIE V., SUEDE, ANGEL GRACE P., TAÑEDO, JANELLE R.",
    citation: "Castor, Z. M. C., Ibañez, K. I. R. C., Indicar, K. A., Manimbayan, J. M., Padilla, J., Suede, A. G. P., Tañedo, J. R. (2024). Zingiber zerumbet: AN UNDERUTILIZED PLANT AS ORGANIC PESTICIDE AGAINST Drosophila melanogaster.",
    abstract: "\n      Zingiber zerumbet or bitter ginger is an underutilized plant with many unexplored potentials. This plant contains a number of normally occurring substances such as terpenoids, and phenolic compounds that are thought to be effective pest repellents. Fruit fly infestations are one of the most common problems in the community. This study aimed to provide an eco-friendly solution to fly infestation. Zingiber zerumbet rhizomes were gathered, washed, and dried, while the fruit flies were collected and cultured for 14 days. The fruit flies were then transferred into 12 containers, each filled with three fruit flies. Four treatments were then formulated, one ml of each treatment was sprayed into each container.\n    \n      Results were checked 24 hours after treatment application, the number of dead fruit flies was used to compare the four treatments' effectiveness. For data analysis, the researchers used the following statistical measures such as mean, standard deviation and ANOVA. The pesticidal activities of the treatments were recorded and evaluated. Results revealed that the positive control (Sevin) has the highest number of dead fruit flies and is considered highly effective. Treatment A (100% Zingiber zerumbet rhizome extract) and treatment B (50% Zingiber zerumbet rhizome extract) follows and were both considered effective. Treatment C (-) was also considered effective. ANOVA results showed no significant difference among the pesticidal activities of the different treatments.\n    \n      Furthermore, researchers recommended to use more fruit flies to clearly show the difference and better extraction methods to show the potential of Zingiber zerumbet as a potential pesticide\n    ",
    researchId: "2024-011",
    author: "ZHEA MARIE C. CASTOR, KAIR IVAN RAE C. IBAÑEZ, KARMELLA A. INDICAR, JUSTINE M. MANIMBAYAN, JESSIE V. PADILLA, ANGEL GRACE P. SUEDE, JANELLE R. TAÑEDO",
    citation: "Castor, Z. M. C., Ibañez, K. I. R. C., Indicar, K. A., Manimbayan, J. M., Padilla, J., Suede, A. G. P., Tañedo, J. R. (2024). Zingiber zerumbet: AN UNDERUTILIZED PLANT AS ORGANIC PESTICIDE AGAINST Drosophila melanogaster.",
    abstract: "Tested bitter ginger rhizome extract as an organic pesticide against fruit flies. Results showed that both 100% and 50% extracts were effective, with no significant difference found compared to commercial pesticides.",
    author:
      "ZHEA MARIE C. CASTOR, KAIR IVAN RAE C. IBAÑEZ, KARMELLA A. INDICAR, JUSTINE M. MANIMBAYAN, JESSIE V. PADILLA, ANGEL GRACE P. SUEDE, JANELLE R. TAÑEDO",
    abstract:`
      Zingiber zerumbet or bitter ginger is an underutilized plant with many unexplored potentials. This plant contains a number of normally occurring substances such as terpenoids, and phenolic compounds that are thought to be effective pest repellents. Fruit fly infestations are one of the most common problems in the community. This study aimed to provide an eco-friendly solution to fly infestation. Zingiber zerumbet rhizomes were gathered, washed, and dried, while the fruit flies were collected and cultured for 14 days. The fruit flies were then transferred into 12 containers, each filled with three fruit flies. Four treatments were then formulated, one ml of each treatment was sprayed into each container.
    
      Results were checked 24 hours after treatment application, the number of dead fruit flies was used to compare the four treatments' effectiveness. For data analysis, the researchers used the following statistical measures such as mean, standard deviation and ANOVA. The pesticidal activities of the treatments were recorded and evaluated. Results revealed that the positive control (Sevin) has the highest number of dead fruit flies and is considered highly effective. Treatment A (100% Zingiber zerumbet rhizome extract) and treatment B (50% Zingiber zerumbet rhizome extract) follows and were both considered effective. Treatment C (-) was also considered effective. ANOVA results showed no significant difference among the pesticidal activities of the different treatments.
    
      Furthermore, researchers recommended to use more fruit flies to clearly show the difference and better extraction methods to show the potential of Zingiber zerumbet as a potential pesticide
    `,
  },
  {
    title: "DETERMINATION OF VITAMIN C FROM Spondias pinnata AND Tetrastigma harmandii LEAVES USING IODOMETRY",
    publishedAt: 2024,
    researchId: "2024-012",
    author: "GALINDO, RHEA KATE I., BEBA, LYRA BELLE, VIVA, MA. FIONA AVELOR R., ARELLANO, JOAN C., MONTUYA, NISHA MARIE B., NACHON, AIRA V., ROBLES, HANNA FAITH V.",
    citation: "Galindo, R. K. I., Beba, L. B., Viva, M. F. A. R., Arellano, J. C., Montuya, N. M. B., Nachon, A., Robles, H. F. (2024). DETERMINATION OF VITAMIN C FROM Spondias pinnata AND Tetrastigma harmandii LEAVES USING IODOMETRY.",
    abstract: "\n      This study aimed to determine the vitamin C content of Spondias pinnata and Tetrastigma harmandii leaves. The leaf samples were washed with distilled water and pat-dried until they could be extracted using a blender and grounded using a mortar and pestle. It was filtered through cheesecloth to obtain the pure extract. Each Spondias pinnata and Tetrastigma harmandii leaf extract had three replications, where each was put in a conical flask and titrated. The titration method and calculations were based on the University of Canterbury, and the significant difference was determined using t-Test: Two-Sample Assuming Unequal Variances. Results revealed that Spondias pinnata leaves have a higher vitamin C content, which is 4.9 mg/100 g, than Tetrastigma harmandii leaves (2.8 mg/100g). The vitamin C content of the Spondias pinnata leaves is significantly higher than the Tetrastigma harmandii leaves based on the results of t-Test.\n    \n      The study about the Spondias pinnata and Tetrastigma harmandii leaves can be used as a preliminary study and serve as reference for future research. However, it is highly recommended to use UV-Vis Spectrophotometer to determine the vitamin C content of the leaves.\n    \n      The researchers recommend to increase the amount of leaves. The researchers also recommend to study more about the phytochemical properties of Spondias pinnata and Tetrastigma harmandii, such as its antioxidative properties.\n    ",
  },
  {
    title: "ANTI-MICROBIAL ACTIVITY OF Averrhoa carambola (GARANGAN) LEAF EXTRACT ON Pseudomonas spp.",
    publishedAt: 2024,
    researchId: "2024-013",
    author: "DIONGLAY, FLOEY M., LOPEZ, ERL ANDREI V., RABAGO, JAMES BERNARD S., AGRETE, JEANIE ROSE B., CASTELLANO, KASSANDRA THERESE T., MARCON, MA. JULIA ZONET, SAUL, CLAIRE IRISH G.",
    citation: "Dionglay, F. M., Lopez, E. A., Rabago, J. B. S., Agrete, J. R. B., Castellano, K. T. T., Marcon, M. J. Z., Saul, C. I. G. (2024). ANTI-MICROBIAL ACTIVITY OF Averrhoa carambola (GARANGAN) LEAF EXTRACT ON Pseudomonas spp.",
    abstract: "\n      This study was conducted to determine the effectiveness of Garangan (Averrhoa carambola) leaf extract as an antimicrobial on Pseudomonas spp.\n\n      The study was conducted at the Central Laboratory of Central Philippine University in Jaro, Iloilo, on April 24-25, 2024. One (1) kilogram of Averrhoa carambola leaves was extracted using a rotary evaporator and formulated into different treatments. There will be 12 plates that will be divided into four groups for the application of treatments: 100% concentration of Averrhoa carambola leaf extract, 50% concentration of Averrhoa carambola leaf extract, Tylosin, and distilled water. The effectiveness of each treatment was determined using the agar-well diffusion method, and the zone of inhibition was measured 24 hours after application. Results showed that all the experimental treatments formed a zone of inhibition on Pseudomonas spp. and were higher compared to those of the negative control. This means that the experimental treatment possesses potential antimicrobial activity against Pseudomonas spp. in terms of zone of inhibition (in milliliters) twenty-four hours after incubation.\n    \n      The researchers recommend using Garangan leaf extract against Pseudomonas spp. bacteria diseases, promoting further study of the plant's roots, fruits, or stems, and enhancing treatments to prove its effectiveness.\n    ",
    researchId: "2024-012",
    author: "RHEA KATE I. GALINDO, LYRA BELLE BEBA, MA. FIONA AVELOR R. VIVA, JOAN C. ARELLANO, NISHA MARIE B. MONTUYA, AIRA V. NACHON, HANNA FAITH V. ROBLES",
    citation: "Galindo, R. K. I., Beba, L. B., Viva, M. F. A. R., Arellano, J. C., Montuya, N. M. B., Nachon, A., Robles, H. F. (2024). DETERMINATION OF VITAMIN C FROM Spondias pinnata AND Tetrastigma harmandii LEAVES USING IODOMETRY.",
    abstract: "Used iodometric titration to compare Vitamin C content. Results showed Spondias pinnata leaves contain significantly higher Vitamin C (4.9 mg/100g) compared to Tetrastigma harmandii (2.8 mg/100g).",
  }
    author:
      "RHEA KATE I. GALINDO, LYRA BELLE BEBA, MA. FIONA AVELOR R. VIVA, JOAN C. ARELLANO, NISHA MARIE B. MONTUYA, AIRA V. NACHON, HANNA FAITH V. ROBLES",
    abstract:`
      This study aimed to determine the vitamin C content of Spondias pinnata and Tetrastigma harmandii leaves. The leaf samples were washed with distilled water and pat-dried until they could be extracted using a blender and grounded using a mortar and pestle. It was filtered through cheesecloth to obtain the pure extract. Each Spondias pinnata and Tetrastigma harmandii leaf extract had three replications, where each was put in a conical flask and titrated. The titration method and calculations were based on the University of Canterbury, and the significant difference was determined using t-Test: Two-Sample Assuming Unequal Variances. Results revealed that Spondias pinnata leaves have a higher vitamin C content, which is 4.9 mg/100 g, than Tetrastigma harmandii leaves (2.8 mg/100g). The vitamin C content of the Spondias pinnata leaves is significantly higher than the Tetrastigma harmandii leaves based on the results of t-Test.
    
      The study about the Spondias pinnata and Tetrastigma harmandii leaves can be used as a preliminary study and serve as reference for future research. However, it is highly recommended to use UV-Vis Spectrophotometer to determine the vitamin C content of the leaves.
    
      The researchers recommend to increase the amount of leaves. The researchers also recommend to study more about the phytochemical properties of Spondias pinnata and Tetrastigma harmandii, such as its antioxidative properties.
    `,
  },
  {
    title:
    "ANTI-MICROBIAL ACTIVITY OF Averrhoa carambola (GARANGAN) LEAF EXTRACT ON Pseudomonas spp.",
    publishedAt: 2024,
    author:
    "FLOEY M. DIONGLAY, ERL ANDREI V. LOPEZ, JAMES BERNARD S. RABAGO, JEANIE ROSE B. AGRETE, KASSANDRA THERESE T. CASTELLANO, MA. JULIA ZONET MARCON, CLAIRE IRISH G. SAUL",
    abstract:`
      This study was conducted to determine the effectiveness of Garangan (Averrhoa carambola) leaf extract as an antimicrobial on Pseudomonas spp.

      The study was conducted at the Central Laboratory of Central Philippine University in Jaro, Iloilo, on April 24-25, 2024. One (1) kilogram of Averrhoa carambola leaves was extracted using a rotary evaporator and formulated into different treatments. There will be 12 plates that will be divided into four groups for the application of treatments: 100% concentration of Averrhoa carambola leaf extract, 50% concentration of Averrhoa carambola leaf extract, Tylosin, and distilled water. The effectiveness of each treatment was determined using the agar-well diffusion method, and the zone of inhibition was measured 24 hours after application. Results showed that all the experimental treatments formed a zone of inhibition on Pseudomonas spp. and were higher compared to those of the negative control. This means that the experimental treatment possesses potential antimicrobial activity against Pseudomonas spp. in terms of zone of inhibition (in milliliters) twenty-four hours after incubation.
    
      The researchers recommend using Garangan leaf extract against Pseudomonas spp. bacteria diseases, promoting further study of the plant's roots, fruits, or stems, and enhancing treatments to prove its effectiveness.
    `,
  }
];
