export const researchData2024 = [
  {
    title: "ALLELOPATHIC ACTIVITY OF JACKFRUIT (Artocarpus heterophyllus) LEAF EXTRACT ON PECHAY (BRASSICA RAPA SUBSP. CHINENSIS)",
    publishedAt: 2024,
    researchId: "2024-001",
    author: "PAUL FEBRIEL D. ADOLFO, ALDRIENE NICOLE S. CARTERA, JULIE ANNE M. ALOC, MARY JUN M. BERONA, REY ANN JOY B. CUSTODIO, GLICIE JOY ANNE B. LAGUARDIA, JANEANE LOUISE A. VELONERO",
    citation: "Adolfo, P. F. D., Cartera, A. N. S., Aloc, J. A. M., Berona, M. J. M., Custodio, R. A. J. B., Laguardia, G. J. A. B., Velonero, J. L. A. (2024). ALLELOPATHIC ACTIVITY OF JACKFRUIT (Artocarpus heterophyllus) LEAF EXTRACT ON PECHAY (BRASSICA RAPA SUBSP. CHINENSIS).",
    abstract: "This study aimed to determine the allelopathic activity of Jackfruit leaf extract on Pechay. Results revealed that Treatment B (0.15g/ml) had the highest allelopathic properties, showing a significant difference in both number of leaves and plant height.",
  },
  {
    title: "Laurus nobilis (BAY LEAF) ESSENTIAL OIL ON GUAR GUM-BASED EDIBLE COATING: ITS EFFECT ON THE INHIBITION OF YEAST AND MOLD GROWTH ON Solanum lycopersicum (TOMATO)",
    publishedAt: 2024,
    researchId: "2024-002",
    author: "DULAY, JAY PHILIP B., AQUINO, CHAD COLEEN MCKAY M., CUARTE, KRYSIA P., LORILLA, QUEENY ZYRA C, OLLOSA, KENNIE G, PEDROLA, STACIE DENISE H., ZAPANTA, SOFIA CLAIRE S.",
    citation: "Dulay, J. P. B., Aquino, C. C. M. M., Cuarte, K. P., Lorilla, Q. Z. C., Ollosa, K. G., Pedrola, S. D. H., Zapanta, S. C. S. (2024). Laurus nobilis (BAY LEAF) ESSENTIAL OIL ON GUAR GUM-BASED EDIBLE COATING: ITS EFFECT ON THE INHIBITION OF YEAST AND MOLD GROWTH ON Solanum lycopersicum (TOMATO).",
    abstract: "This study investigated the addition of Bay Leaf essential oil to Guar Gum-based edible coatings to inhibit yeast and mold on tomatoes. Results showed that microbial growth across all treatments was comparable, though the oil is known for antimicrobial properties.",
  },
  {
    title: "EVALUATION OF THE ANTIPYRETIC EFFECT OF Arcangelisia flava (ALBUTRA) STEM EXTRACT ON Rattus novergicus domesticus (NORWEIGIAN BLACK-HOODED DOMESTICATED RAT)",
    publishedAt: 2024,
    researchId: "2024-003",
    author: "THEO RUCEL C. PRIETO, KYLA JANE C. BILLOSO, ALAIZA C. CONLACION, MARJOLENE J. GALINDO, KERK JUSTINE G. GUIJARNO, MYKAELLA XZY R. PANIAGUA, GWYNETH A. SETERA",
    citation: "Prieto, T. R. C., Billoso, K. J. C., Conlacion, A. C., Galindo, M. J., Guijarno, K. J. G., Paniagua, M. X. R., Setera, G. A. (2024). EVALUATION OF THE ANTIPYRETIC EFFECT OF Arcangelisia flava (ALBUTRA) STEM EXTRACT ON Rattus novergicus domesticus (NORWEIGIAN BLACK-HOODED DOMESTICATED RAT).",
    abstract: "Determined the antipyretic activity of Albutra stem extracts on rats. Treatment with 500mg/kg extract showed the highest mean decrease in temperature, although the results were not significantly different from the control groups.",
  },
  {
    title: "COMPARATIVE ANALYSIS OF ARTIFICIAL NUTRIENT SOLUTION AND Kappaphycus alvarezii (GUSO) EXTRACT IN GROWING OF Lactuca sativa L. (LETTUCE) HYDROPONICALLY",
    publishedAt: 2024,
    researchId: "2024-004",
    author: "MENARD M. MATULLANO, JOEL BRIAN ALCALDE, MIKKA M. ELISEO, ELAINE MAREE M. ESCAÑO, LYCIA REYN S. LOCSIN, CARL JULIUS G. OÑATE, EDELWEISS B. SOMES",
    citation: "Matullano, M. M., Alcalde, J. B., Eliseo, M. M., Escaño, E. M. M., Locsin, L. R. S., Oñate, C. J. G., Somes, E. B. (2024). COMPARATIVE ANALYSIS OF ARTIFICIAL NUTRIENT SOLUTION AND Kappaphycus alvarezii (GUSO) EXTRACT IN GROWING OF Lactuca sativa L. (LETTUCE) HYDROPONICALLY.",
    abstract: "Compared Guso extract and artificial nutrient solution in hydroponic lettuce farming. While the artificial solution had the highest mean growth, Guso extract showed potential as a viable organic alternative.",
  },
  {
    title: "SHELF-LIFE ENHANCEMENT OF Carica papaya USING ZINC OXIDE AS NANOPARTICLES",
    publishedAt: 2024,
    researchId: "2024-005",
    author: "LAMPARERO, JAPETH M., CHICHIRITA, ELLA CARYLLE FAYE E., DY, TRINA MARIE C., ESTREVILLO, MARY HOPE C., MANA-AY, TRISIA CLAIRE P., MASIADO, CHRISTINE JOY N., MONTEFRIO, ANGELICA MARIE M.",
    citation: "Lamparero, J. M., Chichirita, E. C. F. E., Dy, T. M. C., Estrevillo, M. H. C., Mana-Ay, T. C. P., Masiado, C. J. N., Montefrio, A. M. M. (2024). SHELF-LIFE ENHANCEMENT OF Carica papaya USING ZINC OXIDE AS NANOPARTICLES.",
    abstract: "Designed to determine the effect of Zinc Oxide nanoparticles on the shelf-life of papaya. Results indicated that while some concentrations slowed mass loss, there was no significant difference compared to the negative control.",
  },
  {
    title: "A COMPARATIVE ANALYSIS ON THE EFFECTIVITY OF SABA BANANA (Musa acuminata x balbisiana) PEELS AND SUGARCANE (Saccharum officinarum) PEELS AS ALTERNATIVE FEEDS FOR AFRICAN CATFISH (Clarias gariepinus)",
    publishedAt: 2024,
    researchId: "2024-006",
    author: "CAYABYAB, PRANCE NATHANIEL, DARADAR, LOUIE JOHN, ESCANDA, ACESHELLE MARIE, MEDIANESTA, ANN MONIQUE, MENDOZA, GLORIA ELIZABETH, SERVITA, PRILENE, VELASCO, JARA KEZIAH",
    citation: "Cayabyab, P. N., Daradar, L. J., Escanda, A. M., Medianesta, A. M., Mendoza, G. E., Servita, P., Velasco, J. K. (2024). A COMPARATIVE ANALYSIS ON THE EFFECTIVITY OF SABA BANANA (Musa acuminata x balbisiana) PEELS AND SUGARCANE (Saccharum officinarum) PEELS AS ALTERNATIVE FEEDS FOR AFRICAN CATFISH (Clarias gariepinus).",
    abstract: "Examined banana and sugarcane peels as catfish feed. ANOVA showed no significant difference between treatments, but Saba banana peels yielded slightly higher average weight gain in the African catfish.",
  },
  {
    title: "COMPARATIVE ANALYSIS ON ANTIMITOTIC PROPERTY OF CURCUMA LONGA RHIZOME AND SAMANEA SAMAN LEAF EXTRACT USING ALLIUM CEPA ASSAY",
    publishedAt: 2024,
    researchId: "2024-007",
    author: "SEGURA, EARL JAN L., AMBOY, PAULINE MAE M., FLORES, NICOLE FAYE S., LEYSO, MARY FRANCINE SNOW S., MADALOGDOG, JASMIN ANN A., ROBLES, ZHYRA M., VALENZUELA, KHEA MAE A.",
    citation: "Segura, E. J. L., Amboy, P. M. M., Flores, N. F. S., Leyso, M. F. S. S., Madalogdog, J. A. A., Robles, Z. M., Valenzuela, K. M. A. (2024). COMPARATIVE ANALYSIS ON ANTIMITOTIC PROPERTY OF CURCUMA LONGA RHIZOME AND SAMANEA SAMAN LEAF EXTRACT USING ALLIUM CEPA ASSAY.",
    abstract: "Investigated antimitotic properties using the Allium cepa (onion) assay. Samanea saman (Rain Tree) leaf extract was found to be significantly more effective in inhibiting root growth compared to Curcuma longa (Turmeric).",
  },
  {
    title: "Antipyretic Potential of Kara-Kamote (Ipomoea triloba) Aqueous Solution to White Mice (Mus musculus)",
    publishedAt: 2024,
    researchId: "2024-008",
    author: "BORDON, FINNYROSE BERNADETTE B., BRILLO, JEO V., CABARLES, RAINNIER BENEDICT E., DOMINGUEZ, ARNEL ROSS FRANCIS A., MALCONTENTO, HANS CHRISTIAN M., PAGUIDIAN, ANGELA KRISTEN C., PIZ, FRENCH ALDRIN E., SANTISO, ANTHONY JOSH G.",
    citation: "Bordon, F. B. B., Brillo, J., Cabarles, R. B. E., Dominguez, A. R. F. A., Malcontento, H. C. M., Paguidian, A. K. C., Piz, F. A. E., Santiso, A. J. G. (2024). Antipyretic Potential of Kara-Kamote (Ipomoea triloba) Aqueous Solution to White Mice (Mus musculus).",
    abstract: "Tested the antipyretic potential of Kara-kamote aqueous solution on mice. The 100mg/kg concentration showed the highest mean temperature decrease, though statistically comparable to the control group.",
  },
  {
    title: "UTILIZATION OF Vigna unguiculata sesquipedalis BEAN AS FEED RATION SUPPLEMENT FOR Cairina moschata",
    publishedAt: 2024,
    researchId: "2024-009",
    author: "KHYLYN ELORA T. ADOLFO, MARY JOY C. ESTREVILLO, CIARA PRINCESS G. FORTALEZA, ALYSSA MAE M. NUFUAR, RAIZA JANE Y. SARATE, KRYSTINE YANAH L. VICENTE",
    citation: "Adolfo, M. J. C. E. K. E. T., Fortaleza, A. M. M. N. C. P. G., Sarate, K. Y. L. V. R. J. Y. (2024). UTILIZATION OF Vigna unguiculata sesquipedalis BEAN AS FEED RATION SUPPLEMENT FOR Cairina moschata.",
    abstract: "Explored using matured beans as feed supplement for ducks. Results showed that the inclusion of the beans improved growth performance and has potential as a cost-effective alternative to commercial feed.",
  },
  {
    title: "Marigold (Tagetes erecta) Flower as a Replacement feeds on the Growth of Tilapia fingerlings",
    publishedAt: 2024,
    researchId: "2024-010",
    author: "ASCENCIO, JOHN MARTIN, BIBAL, JESSA MAE G., CALIBJO, ALBERT MATTHEW V., FORRO, FRANZ DAVE R., MADERO, NJ C., MONTUYA, JOHN ZANDER A., PANIZA, GELLOURD L.",
    citation: "Ascencio, J. M., Bibal, J. M. G., Calibjo, A. M., Forro, F. D. R., Madero, N. C., Montuya, J. Z. A., Paniza, G. L. (2024). Marigold (Tagetes erecta) Flower as a Replacement feeds on the Growth of Tilapia fingerlings.",
    abstract: "Determined the effect of Marigold flower as replacement feed for Tilapia. ANOVA revealed that the weight gain from Marigold treatments was not significantly different from commercial feed, suggesting its potential as a substitute.",
  },
  {
    title: "Zingiber zerumbet: AN UNDERUTILIZED PLANT AS ORGANIC PESTICIDE AGAINST Drosophila melanogaster",
    publishedAt: 2024,
    researchId: "2024-011",
    author: "CASTOR, ZHEA MARIE C., IBAÑEZ, KAIR IVAN RAE C., INDICAR, KARMELLA A., MANIMBAYAN, JUSTINE M., PADILLA, JESSIE V., SUEDE, ANGEL GRACE P., TAÑEDO, JANELLE R.",
    citation: "Castor, Z. M. C., Ibañez, K. I. R. C., Indicar, K. A., Manimbayan, J. M., Padilla, J., Suede, A. G. P., Tañedo, J. R. (2024). Zingiber zerumbet: AN UNDERUTILIZED PLANT AS ORGANIC PESTICIDE AGAINST Drosophila melanogaster.",
    abstract: "Tested bitter ginger rhizome extract as an organic pesticide against fruit flies. Results showed that both 100% and 50% extracts were effective, with no significant difference found compared to commercial pesticides.",
  },
  {
    title: "DETERMINATION OF VITAMIN C FROM Spondias pinnata AND Tetrastigma harmandii LEAVES USING IODOMETRY",
    publishedAt: 2024,
    researchId: "2024-012",
    author: "GALINDO, RHEA KATE I., BEBA, LYRA BELLE, VIVA, MA. FIONA AVELOR R., ARELLANO, JOAN C., MONTUYA, NISHA MARIE B., NACHON, AIRA V., ROBLES, HANNA FAITH V.",
    citation: "Galindo, R. K. I., Beba, L. B., Viva, M. F. A. R., Arellano, J. C., Montuya, N. M. B., Nachon, A., Robles, H. F. (2024). DETERMINATION OF VITAMIN C FROM Spondias pinnata AND Tetrastigma harmandii LEAVES USING IODOMETRY.",
    abstract: "Used iodometric titration to compare Vitamin C content. Results showed Spondias pinnata leaves contain significantly higher Vitamin C (4.9 mg/100g) compared to Tetrastigma harmandii (2.8 mg/100g).",
  }
];
