export const researchData2025 = [
  {
    title: "Urtica dioica (STINGING NETTLE) LEAVES AS AN ALTERNATIVE FISH FEED FOR Clarias gariepinus (AFRICAN CATFISH) JUVENILE",
    publishedAt: 2025,
    researchId: "2025-001",
    author: "ANDREA C. CAMEN, KYLE JERWIN T. MALCONTENTO, GAYLE T. MAYOLA, NINIA JEAN B. MONTUYA, MARYLAN S. PENIT, MC ERICO P. RUTE, KRIS LAWRENZ C. SEPAYA, RHEA JANE M. TALAMOR, BRITTANY C. VERGARA",
    citation: "Camen, A. C., Malcontento, K. J. T., Mayola, G. T., Montuya, N. J. B., Penit, M. S., Rute, M. E. P., Sepaya, K. L. C., Talamor, R. J. M., Vergara, B. C. (2025). Urtica dioica (STINGING NETTLE) LEAVES AS AN ALTERNATIVE FISH FEED FOR Clarias gariepinus (AFRICAN CATFISH) JUVENILE.",
    abstract: "The purpose of this study was to test if Urtica dioica leaves can be used as an alternative feed protein source for African catfish. Results showed that Urtica dioica leaves have a significant effect on the average weight gain of Clarias gariepinus juveniles after one week of feeding.",
  },
  {
    title: "Saccharum Officinarum (Sugarcane) AND Cymbopogon Citratus (Lemongrass) AS A SOURCE FOR PLANT FIBERS",
    publishedAt: 2025,
    researchId: "2025-002",
    author: "JASMINE ROSE R. ALAESTANTE, DONNA JANEL C. GANJE, RANDYLE G. LIBUNA, ILDHEN JAMES L. LUNAR, ALEXIA GERMAINE V. MANALO, JENIELIZA P. ORBE, JENE LAWRENCE V. SAUL, RICHARD MARK B. VILLENAS",
    citation: "Alaestante, D. J. C. G. J. R. R., Libuna, I. J. L. L. R. G., Manalo, J. P. O. A. G., Saul, R. M. B. V. J. L. (2025). Saccharum Officinarum (Sugarcane) AND Cymbopogon Citratus (Lemongrass) AS A SOURCE FOR PLANT FIBERS.",
    abstract: "This study assessed the potential of sugarcane and lemongrass as a source of plant fibers. Results showed that both fibers are classified as Low Tensile Strength and there is no significant difference between the tensile strength of Saccharum officinarum and Cymbopogon citratus.",
  },
  {
    title: "ANTACID POTENTIAL OF Muntingia Calabura (SARISA) LEAF EXTRACT",
    publishedAt: 2025,
    researchId: "2025-003",
    author: "LANCE MATTHEW H. PEDROLA, ZHIEAN A. ENGADA, MARK DAVE C. SALA, ARIENE FAITH O. ABDON, SHAMA G. DINOY, JHEANNE NICOLE P. ERESPE, SHEENA JEAN C. RICAFRENTE, FRITZMANE DAWN E. SOLDEVILLA",
    citation: "Pedrola, Z. A. E. L. M. H., Sala, A. F. O. A. M. D. C., Dinoy, J. N. P. E. S. G., Ricafrente, F. D. E. S. S. J. C. (2025). ANTACID POTENTIAL OF Muntingia Calabura (SARISA) LEAF EXTRACT.",
    abstract: "This study evaluated the antacid potential of Muntingia calabura leaf extract. Results showed the extract had a mean pH level of 1.5, which is below the 3.5 threshold, indicating it does not meet the criteria to be classified as an antacid.",
  },
  {
    title: "CYTOTOXIC ACTIVITY OF Spondias Purpurea (SINIGUELAS) LEAF EXTRACT USING Artemia salina (BRINE SHRIMP) LETHALITY ASSAY",
    publishedAt: 2025,
    researchId: "2025-004",
    author: "KIM CYNEL H. ABENTINO, JAYSON ANDREW A. ARELLANO, RYAN RAINZOR A. LAZARTE, STEPHANIE KATE L. CARVAJAL, CLAIRE M. GALVEZ, TRISHA M. LIZADA, GLEAH MARIE D. PARRA, SACHI MISHKA D. PREGUA",
    citation: "Abentino, J. A. A. A. K. C. H., Lazarte, S. K. L. C. R. R. A., Galvez, T. M. L. C. M., Parra, S. M. D. P. G. M. D. (2025). CYTOTOXIC ACTIVITY OF Spondias Purpurea (SINIGUELAS) LEAF EXTRACT USING Artemia salina (BRINE SHRIMP) LETHALITY ASSAY.",
    abstract: "This study determined the cytotoxic activity of Spondias purpurea leaf extract. Results showed high cytotoxic activity, with 1000 ppm concentration being the most effective, possessing a significant difference in mortality rate across treatments.",
  },
  {
    title: "BIO-PHOTOVOLTAIC POTENTIAL OF Peperomia pellucida LEAF EXTRACT AS A DYE SENSITIZER",
    publishedAt: 2025,
    researchId: "2025-005",
    author: "BRILLO, JENNY MAE, DOMEGILIO, GIAN MARK, JAYME, KRISTEL, LIBIANO, CZARINA, MOJICA, EUNICE, SOQUERA, ED DOMINIC, TOREJO, MARY FLEUR, VICENTINO, MA. ALYANAH",
    citation: "Brillo, J. M., Domegilio, G. M., Jayme, K., Libiano, C., Mojica, E., Soquera, E. D., Torejo, M. F., Vicentino, M. A. (2025). BIO-PHOTOVOLTAIC POTENTIAL OF Peperomia pellucida LEAF EXTRACT AS A DYE SENSITIZER.",
    abstract: "Determined the bio-photovoltaic potential of Peperomia pellucida leaf extract. Results revealed the voltage output was significantly higher than the negative control and comparable to the positive control (Rhodamine B), concluding it has potential as a dye sensitizer.",
  },
  {
    title: "RED DRAGON FRUIT (Selenicereus undatus) PEELINGS AND RED ONION (Allium cepa) SKIN AS SPECIMEN STAIN",
    publishedAt: 2025,
    researchId: "2025-006",
    author: "BALLINAS, AMIEL JOSHUA Y., TORMON, ALDRED R., TRABADO, LUISITO T., MALLO, ALYSSA EUNICE C., PASCUA, ALAIKAH J., SELORIO, CEFIE THERESE M., SORILLA, LOVEN GRACE C., SUEL, KIMBERLY L.",
    citation: "Ballinas, A. J. Y., Tormon, A. R., Trabado, L. T., Mallo, A. E. C., Pascua, A. J., Selorio, C. T. M., Sorilla, L. G. C., Suel, K. L. (2025). RED DRAGON FRUIT (Selenicereus undatus) PEELINGS AND RED ONION (Allium cepa) SKIN AS SPECIMEN STAIN.",
    abstract: "Explored natural stains from Red Dragon Fruit peelings and Red Onion skin. While 95% ethanol extracts showed significant staining potential, they did not achieve the same intensity as synthetic eosin, but support viability as sustainable alternatives.",
  },
  {
    title: "BIO-PHOTOVOLTAIC POTENTIAL OF Syzygium cumini (JAVA PLUM) LEAF EXTRACT AS DYE-SENSITIZED SOLAR CELL",
    publishedAt: 2025,
    researchId: "2025-007",
    author: "AGRETE, ZHANIN MAY A., BUNCALAN, ANDREA CONNIE C., CUDO, AMBER JEAN A., MAINAR, JELLAN RYNZ G., MALCONTENTO, CHRISTIAN VAL M., MAYORMENTE, LORRIANE MAE, QUIZADA, JOHN RENZ BRYAN V., TRONCOSO, JEPH AYRRA S.",
    citation: "Agrete, Z. M. A., Buncalan, A. C. C., Cudo, A. J. A., Mainar, J. R. G., Malcontento, C. V. M., Mayormente, L. M., Quizada, J. R. B., Troncoso, J. A. S. (2025). BIO-PHOTOVOLTAIC POTENTIAL OF Syzygium cumini (JAVA PLUM) LEAF EXTRACT AS DYE-SENSITIZED SOLAR CELL.",
    abstract: "Tested Java Plum leaf extract as a dye-sensitizer for solar cells. Statistical analysis indicated no significant difference in voltage output compared to negative controls, concluding it is not advised for use as an alternative dye-sensitized solar cell.",
  },
  {
    title: "ANTIMICROBIAL ACTIVITY OF Semecarpus cuneiformis (ANAGAS) LEAF EXTRACT ON Staphylococcus aureus",
    publishedAt: 2025,
    researchId: "2025-008",
    author: "ALVAREZ, LORELYN A., AMADA, CHRISTINE B., CORDERO, RUELYN B., DABI, JAN ERICA I., GANCIA, KATRICE FAYE M., PADILLA, JOHN MARK V., PENELONIO, MARY QUENNIE P., VUELGA, NICHOLAS AARON M.",
    citation: "Alvarez, L. A., Amada, C. B., Cordero, R. B., Dabi, J. E. I., Gancia, K. F. M., Padilla, J. M., Penelonio, M. Q. P., Vuelga, N. A. M. (2025). ANTIMICROBIAL ACTIVITY OF Semecarpus cuneiformis (ANAGAS) LEAF EXTRACT ON Staphylococcus aureus.",
    abstract: "Evaluated antimicrobial activity of Anagas leaf extract against S. aureus. All concentrations inhibited the bacteria, with 0.50 mg/ml being most effective, though significantly less effective than commercial Cefazolin.",
  },
  {
    title: "ANTICOAGULATING EFFECT OF Excoecaria cochinchinensis LEAF EXTRACT (PICARRA) ON HUMAN BLOOD",
    publishedAt: 2025,
    researchId: "2025-009",
    author: "BORDON, JOHN LORENZ, MUEL, BRENT MAVERICK, CLARITO, JASHLEY JOHN, PANIAGUA, KYLE, DAJAY, SAMANTHA NEMIE, VELASCO, CHRIS ANN MARIE, LALANTACON, BRUNNEN, VILLASIS, CLOIDIE HYNNE, YGAÑA, ALEXANDRIA",
    citation: "Bordon, J. L., Muel, B. M., Clarito, J. J., Paniagua, K., Dajay, S. N., Velasco, C. A. M., Lalantacon, B., Villasis, C. H., Ygaña, A. (2025). ANTICOAGULATING EFFECT OF Excoecaria cochinchinensis LEAF EXTRACT (PICARRA) ON HUMAN BLOOD.",
    abstract: "Investigated the anticoagulant properties of Picarra leaf extract. Results indicate the extract effectively prolongs blood clotting time, suggesting the presence of natural anticoagulant compounds as potential alternatives to synthetic drugs.",
  },
  {
    title: "GROWTH PERFORMANCE OF Brassica oleracea var. capitata (Cabbage) IN AQUAPONIC SYSTEM USING BANANA PSEUDOSTEM AS GROWTH MEDIUM",
    publishedAt: 2025,
    researchId: "2025-010",
    author: "JULIO CESAR M. AMISTOSO, ANTONIO ANGELO J. BACLAGON, MARIUN C. MESADA, KAYE DOMINIQUE C. MANA-AY, SAMANTHA KRISTINE JOY R. PALLADA, VANESSA J. RONCAL, LEAH ROSE V. SILVIAS, CRYSTAL MAE O. VELASCO",
    citation: "Amistoso, A. A. J. B. J. C. M., Mesada, K. D. C. M. M. C., Pallada, V. J. R. S. K. J. R., Silvias, C. M. O. V. L. R. (2025). GROWTH PERFORMANCE OF Brassica oleracea var. capitata (Cabbage) IN AQUAPONIC SYSTEM USING BANANA PSEUDOSTEM AS GROWTH MEDIUM.",
    abstract: "Determined the growth performance of cabbage using banana pseudostems in aquaponics. Results show no significant difference between aquaponic and conventional soil-based systems for height and leaf length, but a significant difference in leaf count.",
  },
  {
    title: "INSECTICIDAL ACTIVITY OF Alocasia macrorrhizos (BADJANG) LEAF EXTRACT ON Leptocorisa acuta (RICE BUG)",
    publishedAt: 2025,
    researchId: "2025-011",
    author: "CLOMA, SEAN CARLO C., CONLU, KRISTINE MARIE B., EMBERGA, KATE WARLEM R., GIYANGAN, JEREMY DON P., GUTIERREZ, CHELZEE FAYE R., MANGCO, KENT BRIAN P., SEPAYA, CINDY PEARL F., TION, SHARAH MARIE R.",
    citation: "Cloma, S. C. C., Conlu, K. M. B., Emberga, K. W. R., Giyangan, J. D. P., Gutierrez, C. F. R., Mangco, K. B. P., Sepaya, C. P. F., Tion, S. M. R. (2025). INSECTICIDAL ACTIVITY OF Alocasia macrorrhizos (BADJANG) LEAF EXTRACT ON Leptocorisa acuta (RICE BUG).",
    abstract: "Investigated insecticidal activity against rice bugs. The 100 mg/ml concentration resulted in the highest mortality rate, indicating that Alocasia macrorrhizos has promising potential as a natural insecticide.",
  },
  {
    title: "Caesalpinia Sappan (Sappan Wood) AS ORGANIC INK",
    publishedAt: 2025,
    researchId: "2025-012",
    author: "MARIELLE ALIMOSA, SKY KATE C. BOLIVAR, TRISHA CANDAME, LUCILLE ALEXANDRA O. CASQUITE, ZABDIEL JAMES C. LABATA, ORLANDO T. MORENO JR., KATELYN ORTEGA, TRLYSHA JEIL S. QUILARTO",
    citation: "Alimosa, S. K. C. B. M., Candame, L. A. O. C. T., Labata, O. T. M. Z. J. C., Ortega, T. J. S. Q. K. (2025). Caesalpinia Sappan (Sappan Wood) AS ORGANIC INK.",
    abstract: "Determined the potential of Sappan wood heartwood extract as organic ink. Findings showed favorable physical properties, with Treatment B (87.5% pigment) performing best in terms of consistency, odor, and drying time.",
  },
  {
    title: "Cassia fistula (GOLDEN SHOWER TREE) SEED OIL AS WOOD PRESERVATIVE ON Cocos nucifera (COCONUT) LUMBER",
    publishedAt: 2025,
    researchId: "2025-013",
    author: "JEMROCHE L. APSAY, LAIZA JOY Z. BERGANIO, NOELA R. CLAMOR, RAZEL C. CORONADO, CARL LOUIE M. MEJARES, GIAN MARTIN F. MELICADO, AILEN V. NACHON, ZYRAH C. SURRIGA",
    citation: "Apsay, L. J. Z. B. J. L., Clamor, R. C. C. N. R., Mejares, G. M. F. M. C. L. M., Nachon, Z. C. S. A. (2025). Cassia fistula (GOLDEN SHOWER TREE) SEED OIL AS WOOD PRESERVATIVE ON Cocos nucifera (COCONUT) LUMBER.",
    abstract: "Tested Golden Shower Tree seed oil as a wood preservative. The oil significantly reduced tangential swelling and showed a higher termite repellency rate (90%) compared to commercial preservatives (76.67%).",
  },
  {
    title: "COMPARATIVE STUDY OF Ananas comosus LEAF FIBER QUALITY OF CABATUAN AND PASSI CITY",
    publishedAt: 2025,
    researchId: "2025-014",
    author: "DAIBERT ESCANDA, KYLE LOURENZ PAGONZAGA, NEO PRINCE TUD, AMARIAH BAYLEN, REIGNE JAZCHEN CEZAR, SHANEN MAREI CLARITO, LOUGILLE RETAZO, DHEXIE ANJELA VILLAREAL",
    citation: "Escanda, K. L. P. D., Tud, A. B. N. P., Cezar, S. M. C. R. J., Retazo, D. A. V. L. (2025). COMPARATIVE STUDY OF Ananas comosus LEAF FIBER QUALITY OF CABATUAN AND PASSI CITY.",
    abstract: "Compared pineapple leaf fiber quality from two locations. Results indicated no significant difference in tensile strength or soil composition, reinforcement the viability of pineapple leaf fibers as a consistent industrial material.",
  },
  {
    title: "HEAT QUANTITY OF DRIED Cocos nucifera (COCONUT) SPADIX AS SOLID FUEL (BRIQUETTE)",
    publishedAt: 2025,
    researchId: "2025-015",
    author: "KARL ALAVE L., CAROLYN ACBANG C., THERESE MARIE AGUIRRE P., ABEGIEL NYLYN BAÑAS H., RALPH JADE LENTIJA H., DANIELLA OYANIB M., LEANN MEI PAGUIDIAN T., SHERENE MARIE SORNITO C.",
    citation: "L., C. A. C. K. A., P., A. N. B. H. T. M. A., H., D. O. M. R. J. L., T., S. M. S. C. L. M. P. (2025). HEAT QUANTITY OF DRIED Cocos nucifera (COCONUT) SPADIX AS SOLID FUEL (BRIQUETTE).",
    abstract: "Evaluated heat output and burn duration of coconut spadix briquettes. Results indicated a significant difference compared to commercial solid fuel, suggesting the spadix briquettes are a viable sustainable fuel source.",
  },
  {
    title: "POTENTIAL OF Garcinia binucao (BATUAN) AS ELECTROLYTE IN BIO-BATTERIES",
    publishedAt: 2025,
    researchId: "2025-016",
    author: "IVAN LOUIE SINSAY, GIAN JOSHUA YEBRA, ALYSSA JANE BANSAGON, DIANNA MAE CONDE, JUNE MAE LLAVORE, JANELLE KIM MAALIHAN, ANNA MARIE PLANCO, RHIANNE LEI RUTE",
    citation: "Sinsay, G. J. Y. I. L., Bansagon, D. M. C. A. J., Llavore, J. K. M. J. M., Planco, R. L. R. A. M. (2025). POTENTIAL OF Garcinia binucao (BATUAN) AS ELECTROLYTE IN BIO-BATTERIES.",
    abstract: "Investigated Batuan fruit paste as an organic electrolyte. The bio-battery produced an average voltage of 1.085 V. While functional, its output was lower than that of commercial batteries, indicating a need for further optimization.",
  }
];
