import { useMutation } from "@tanstack/react-query";
import { createResearchMutationOptions } from "../lib/api/mutations/archives.mutations";
import { useCreateResearchForm } from "../lib/forms/researchForms";
import { useAutoGeneratedField } from "../lib/forms/useAutoGeneratedField";
import {
	generateApaCitation,
	generateResearchId,
} from "../lib/utils/research-generation";

export default function CreateResearch() {
	const { mutateAsync } = useMutation(createResearchMutationOptions);
	const form = useCreateResearchForm({
		onSubmit: async (payload) => {
			await mutateAsync(payload);
			citationField.resetAutoEnabled();
			researchIdField.resetAutoEnabled();
		},
	});

	const resolveYear = (value: number | "") =>
		typeof value === "number" && Number.isFinite(value)
			? value
			: new Date().getFullYear();

	const getCitationDeps = (overrides?: {
		author?: string;
		title?: string;
		publishedAt?: number | "";
	}) => {
		const currentValues = form.state.values;
		return {
			author: overrides?.author ?? currentValues.author,
			title: overrides?.title ?? currentValues.title,
			publishedAt: overrides?.publishedAt ?? currentValues.publishedAt,
		};
	};

	const getResearchIdDeps = (publishedAtOverride?: number | "") => ({
		publishedAt: publishedAtOverride ?? form.state.values.publishedAt,
	});

	const citationField = useAutoGeneratedField({
		generate: ({
			author,
			title,
			publishedAt,
		}: {
			author: string;
			title: string;
			publishedAt: number | "";
		}) => generateApaCitation(author, resolveYear(publishedAt), title),
		setValue: (citation) => {
			form.setFieldValue("citation", citation);
		},
	});

	const researchIdField = useAutoGeneratedField({
		generate: ({ publishedAt }: { publishedAt: number | "" }) =>
			generateResearchId(resolveYear(publishedAt), 1),
		setValue: (researchId) => {
			form.setFieldValue("researchId", researchId);
		},
	});

	return (
		<div className="mx-auto w-full max-w-4xl px-4 py-8 sm:px-6 sm:py-10 lg:px-8">
			<div className="w-full rounded-2xl border border-[#dfe7dc] bg-white p-6 shadow-sm sm:p-8">
				<h2 className="mb-6 text-2xl font-bold text-[#2d3b2d]">
					Add New Research Archive
				</h2>
				<form.AppForm>
					<form
						onSubmit={(event) => {
							event.preventDefault();
							event.stopPropagation();
							void form.handleSubmit();
						}}
						className="space-y-6"
					>
						<form.Subscribe selector={(state) => state.errorMap.onSubmit}>
							{(submitError) =>
								typeof submitError === "string" ? (
									<div className="bg-red-50 border border-red-200 rounded-lg p-4">
										<p className="text-red-700 text-sm font-medium">
											{submitError}
										</p>
									</div>
								) : null
							}
						</form.Subscribe>

						<form.AppField name="title">
							{(field) => (
								<field.FormTextField
									label="Research Title"
									placeholder="Enter the complete research title"
									onValueChange={(nextTitle) => {
										citationField.onDependenciesChange(
											getCitationDeps({ title: String(nextTitle) }),
										);
									}}
									className="focus-visible:ring-[#7a9b76]"
								/>
							)}
						</form.AppField>

						<form.AppField name="author">
							{(field) => (
								<field.FormTextField
									label="Author(s)"
									placeholder="e.g., Sarah Johnson"
									description="Separate multiple authors with commas"
									onValueChange={(nextAuthor) => {
										citationField.onDependenciesChange(
											getCitationDeps({ author: String(nextAuthor) }),
										);
									}}
									className="focus-visible:ring-[#7a9b76]"
								/>
							)}
						</form.AppField>

						<form.AppField name="publishedAt">
							{(field) => (
								<field.FormTextField
									label="Year Published"
									type="number"
									min="1900"
									max="2099"
									step="1"
									normalizeValue={(value) =>
										value === "" ? "" : Number.parseInt(value, 10)
									}
									onValueChange={(nextPublishedAt) => {
										const parsedPublishedAt =
											typeof nextPublishedAt === "number"
												? nextPublishedAt
												: "";

										researchIdField.onDependenciesChange(
											getResearchIdDeps(parsedPublishedAt),
										);
										citationField.onDependenciesChange(
											getCitationDeps({ publishedAt: parsedPublishedAt }),
										);
									}}
									className="focus-visible:ring-[#7a9b76]"
								/>
							)}
						</form.AppField>

						<form.AppField name="researchId">
							{(field) => (
								<field.FormTextFieldWithReset
									label="Research ID"
									description="Format: YYYY-###. Auto-updates with year until manually edited."
									placeholder="e.g., 2025-001"
									onValueChange={() => {
										researchIdField.onManualValueChange();
									}}
									showReset={!researchIdField.isAutoEnabled}
									onReset={() => {
										researchIdField.resetToAuto(getResearchIdDeps());
									}}
									className="focus-visible:ring-[#7a9b76]"
								/>
							)}
						</form.AppField>

						<form.AppField name="citation">
							{(field) => (
								<field.FormTextareaFieldWithReset
									label="Citation (APA)"
									description="Auto-updates with author, title, and year until manually edited."
									placeholder="e.g., Dela Cruz, J. (2025). Study title."
									onValueChange={() => {
										citationField.onManualValueChange();
									}}
									showReset={!citationField.isAutoEnabled}
									onReset={() => {
										citationField.resetToAuto(getCitationDeps());
									}}
									className="min-h-28 focus-visible:ring-[#7a9b76]"
								/>
							)}
						</form.AppField>

						<form.AppField name="abstract">
							{(field) => (
								<field.FormTextareaField
									label="Abstract"
									placeholder="Paste the abstract here..."
									className="min-h-50 focus-visible:ring-[#7a9b76]"
								/>
							)}
						</form.AppField>

						<div className="flex justify-end pt-4">
							<form.FormSubmitButton
								label="Add Archive"
								submittingLabel="Adding Archive..."
								className="rounded-md bg-[#7a9b76] px-8 py-2 text-white hover:bg-[#6a8b66]"
							/>
						</div>
					</form>
				</form.AppForm>
			</div>
		</div>
	);
}
