import { useCallback, useState } from "react";

interface UseAutoGeneratedFieldParams<TDeps, TValue> {
	generate: (deps: TDeps) => TValue;
	setValue: (value: TValue) => void;
	initialAutoEnabled?: boolean;
}

export function useAutoGeneratedField<TDeps, TValue>({
	generate,
	setValue,
	initialAutoEnabled = true,
}: UseAutoGeneratedFieldParams<TDeps, TValue>) {
	const [isAutoEnabled, setIsAutoEnabled] = useState(initialAutoEnabled);

	const regenerate = useCallback(
		(deps: TDeps) => {
			setValue(generate(deps));
		},
		[generate, setValue],
	);

	const onDependenciesChange = useCallback(
		(deps: TDeps) => {
			if (!isAutoEnabled) {
				return;
			}

			regenerate(deps);
		},
		[isAutoEnabled, regenerate],
	);

	const onManualValueChange = useCallback(() => {
		if (!isAutoEnabled) {
			return;
		}

		setIsAutoEnabled(false);
	}, [isAutoEnabled]);

	const resetToAuto = useCallback(
		(deps: TDeps) => {
			setIsAutoEnabled(true);
			regenerate(deps);
		},
		[regenerate],
	);

	const resetAutoEnabled = useCallback(() => {
		setIsAutoEnabled(true);
	}, []);

	return {
		isAutoEnabled,
		onDependenciesChange,
		onManualValueChange,
		regenerate,
		resetToAuto,
		resetAutoEnabled,
	};
}
