/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveListIndexRouteImport } from './routes/archive-list/index'
import { Route as ArchiveListIdRouteImport } from './routes/archive-list/$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveListIndexRoute = ArchiveListIndexRouteImport.update({
  id: '/archive-list/',
  path: '/archive-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveListIdRoute = ArchiveListIdRouteImport.update({
  id: '/archive-list/$id',
  path: '/archive-list/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive-list/$id': typeof ArchiveListIdRoute
  '/archive-list/': typeof ArchiveListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive-list/$id': typeof ArchiveListIdRoute
  '/archive-list': typeof ArchiveListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive-list/$id': typeof ArchiveListIdRoute
  '/archive-list/': typeof ArchiveListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/archive-list/$id' | '/archive-list/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/archive-list/$id' | '/archive-list'
  id: '__root__' | '/' | '/about' | '/archive-list/$id' | '/archive-list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveListIdRoute: typeof ArchiveListIdRoute
  ArchiveListIndexRoute: typeof ArchiveListIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive-list/': {
      id: '/archive-list/'
      path: '/archive-list'
      fullPath: '/archive-list/'
      preLoaderRoute: typeof ArchiveListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive-list/$id': {
      id: '/archive-list/$id'
      path: '/archive-list/$id'
      fullPath: '/archive-list/$id'
      preLoaderRoute: typeof ArchiveListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveListIdRoute: ArchiveListIdRoute,
  ArchiveListIndexRoute: ArchiveListIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
